In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException
from selenium.webdriver.common.by import By
import time
from bs4 import BeautifulSoup
import requests 
import re

In [2]:
driver=webdriver.Chrome(r"C:\Users\GauRav SingH\Desktop\Internship\Selenium\chromedriver.exe")

### 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [28]:
url_1="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/"

In [29]:
driver.get(url_1)

In [30]:
Rank=[]
Name=[]
Artist=[]
Upload_Date=[]
Views=[]

In [31]:
search_1 = driver.find_element(By.XPATH,'//*[@id="noarticletext"]/tbody/tr/td/span/a')       # Locating page foe top videos by xpath
search_1.click()

In [32]:
search_2 = driver.find_element(By.XPATH,'//*[@id="mw-content-text"]/div[3]/div[2]/ul/li[1]/table/tbody/tr/td[2]/div[1]/a')       # Locating page for top youtube videos by xpath
search_2.click()

In [35]:
#scraping the Rank 
rk=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[1]')
for i in rk:
    if i.text is None :
        Rank.append("--") 
    else:
        Rank.append(i.text)
print(len(Rank),Rank)

30 ['1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.', '10.', '11.', '12.', '13.', '14.', '15.', '16.', '17.', '18.', '19.', '20.', '21.', '22.', '23.', '24.', '25.', '26.', '27.', '28.', '29.', '30.']

In [36]:
#scraping the Video Name 
nm=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[2]')
for i in nm:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

30 ['"Baby Shark Dance"[4]', '"Despacito"[7]', '"Johny Johny Yes Papa"[14]', '"Bath Song"[15]', '"Shape of You"[16]', '"See You Again"[18]', '"Phonics Song with Two Words"[23]', '"Wheels on the Bus"[24]', '"Uptown Funk"[25]', '"Learning Colors – Colorful Eggs on a Farm"[26]', '"Gangnam Style"[27]', '"Masha and the Bear – Recipe for Disaster"[32]', '"Dame Tu Cosita"[33]', '"Sugar"[34]', '"Axel F"[35]', '"Roar"[36]', '"Counting Stars"[37]', '"Sorry"[38]', '"Thinking Out Loud"[39]', '"Baa Baa Black Sheep"[40]', '"Waka Waka (This Time for Africa)"[41]', '"Dark Horse"[42]', '"Faded"[43]', '"Let Her Go"[44]', '"Perfect"[45]', '"Girls Like You"[46]', '"Lakdi Ki Kathi"[47]', '"Bailando"[48]', '"Lean On"[49]', '"Humpty the train on a fruits ride"[50]']

In [37]:
#scraping the Artist 
Ar=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[3]')
for i in Ar:
    if i.text is None :
        Artist.append("--") 
    else:
        Artist.append(i.text)
print(len(Artist),Artist)

30 ["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', 'LooLoo Kids', 'Cocomelon – Nursery Rhymes', 'Ed Sheeran', 'Wiz Khalifa', 'ChuChu TV', 'Cocomelon – Nursery Rhymes', 'Mark Ronson', 'Miroshka TV', 'Psy', 'Get Movies', 'El Chombo', 'Maroon 5', 'Crazy Frog', 'Katy Perry', 'OneRepublic', 'Justin Bieber', 'Ed Sheeran', 'Cocomelon – Nursery Rhymes', 'Shakira', 'Katy Perry', 'Alan Walker', 'Passenger', 'Ed Sheeran', 'Maroon 5', 'Jingle Toons', 'Enrique Iglesias', 'Major Lazer', 'Kiddiestv Hindi – Nursery Rhymes & Kids Songs']

In [38]:
#scraping the Upload_Date 
date=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[5]')
for i in date:
    if i.text is None :
        Upload_Date.append("--") 
    else:
        Upload_Date.append(i.text)
print(len(Upload_Date),Upload_Date)

30 ['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'January 30, 2017', 'April 6, 2015', 'March 6, 2014', 'May 24, 2018', 'November 19, 2014', 'February 27, 2018', 'July 15, 2012', 'January 31, 2012', 'April 5, 2018', 'January 14, 2015', 'June 16, 2009', 'September 5, 2013', 'May 31, 2013', 'October 22, 2015', 'October 7, 2014', 'June 25, 2018', 'June 4, 2010', 'February 20, 2014', 'December 3, 2015', 'July 25, 2012', 'November 9, 2017', 'May 31, 2018', 'June 14, 2018', 'April 11, 2014', 'March 22, 2015', 'January 26, 2018']

In [39]:
#scraping the Views 
v=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[4]')
for i in v:
    if i.text is None :
        Views.append("--") 
    else:
        Views.append(i.text)
print(len(Views),Views)

30 ['12.55', '8.11', '6.66', '6.08', '5.95', '5.82', '5.22', '5.04', '4.87', '4.86', '4.73', '4.54', '4.28', '3.84', '3.82', '3.76', '3.75', '3.64', '3.57', '3.56', '3.52', '3.48', '3.42', '3.40', '3.40', '3.39', '3.37', '3.35', '3.35', '3.34']

In [40]:
Youtube_Video=pd.DataFrame([])
Youtube_Video['Rank']=Rank
Youtube_Video['Video Title']=Name
Youtube_Video['Artist']=Artist
Youtube_Video['Upload_Date']=Upload_Date
Youtube_Video['Views In Bllion']=Views
Youtube_Video

,Rank,Video Title,Artist,Upload_Date,Views In Bllion
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.55
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.11
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.66
3,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,"May 2, 2018",6.08
4,5.,"""Shape of You""[16]",Ed Sheeran,"January 30, 2017",5.95
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.82
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.22
7,8.,"""Wheels on the Bus""[24]",Cocomelon – Nursery Rhymes,"May 24, 2018",5.04
8,9.,"""Uptown Funk""[25]",Mark Ronson,"November 19, 2014",4.87
9,10.,"""Learning Colors – Colorful Eggs on a Farm""[26]",Miroshka TV,"February 27, 2018",4.86
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.73
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.54
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.28
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.84
14,15.,"""Axel F""[35]",Crazy Frog,"June 16, 2009",3.82
15,16.,"""Roar""[36]",Katy Perry,"September 5, 2013",3.76
16,17.,"""Counting Stars""[37]",OneRepublic,"May 31, 2013",3.75
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.64
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.57
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.56
20,21.,"""Waka Waka (This Time for Africa)""[41]",Shakira,"June 4, 2010",3.52
21,22.,"""Dark Horse""[42]",Katy Perry,"February 20, 2014",3.48
22,23.,"""Faded""[43]",Alan Walker,"December 3, 2015",3.42
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.40
24,25.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.40
25,26.,"""Girls Like You""[46]",Maroon 5,"May 31, 2018",3.39
26,27.,"""Lakdi Ki Kathi""[47]",Jingle Toons,"June 14, 2018",3.37
27,28.,"""Bailando""[48]",Enrique Iglesias,"April 11, 2014",3.35
28,29.,"""Lean On""[49]",Major Lazer,"March 22, 2015",3.35
29,30.,"""Humpty the train on a fruits ride""[50]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.34

### 3. Scrape the details of State-wise GDP of India fromstatisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:

A) Rank

B) State

C) GSDP(18-19)- at current prices

D) GSDP(19-20)- at current prices

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through co

In [11]:
url_3=' http://statisticstimes.com/'
driver.get(url_3)

In [25]:
# make an empty list of all the column which are going to be scraped 

Rank=[]
State =[]
GDP=[]
GSDP_Current=[]
GSDP_19_20=[]
Share=[]

In [26]:
economy=driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button')     # location of the nav bar from where we select
economy.click()

In [27]:
ind=driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/div/a[3]')      # the selected item 
ind.click()

In [28]:
gdp=driver.find_element(By.XPATH,'html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
gdp.click()

In [29]:
# scraping the ranks

r=driver.find_elements(By.XPATH,'//td[@class="data1"]')
for i in r:
    if i.text is None:
        Rank.append('--')
    else:
        Rank.append(i.text)
        
print(len(Rank),Rank)

68 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '']

In [30]:
#scraping the State 
St=driver.find_elements(By.XPATH,"//td[@class='name']")
for i in St:
    if i.text is None :
        State.append("--") 
    else:
        State.append(i.text)
print(len(State),State)

68 ['Maharashtra', 'Tamil Nadu', 'Uttar Pradesh', 'Gujarat', 'Karnataka', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Punjab', 'Odisha', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Nagaland', 'Arunachal Pradesh', 'Mizoram', 'Andaman & Nicobar Islands', 'India', 'Maharashtra', 'Tamil Nadu', 'Uttar Pradesh', 'Karnataka', 'Gujarat', 'West Bengal', 'Rajasthan', 'Telangana', 'Andhra Pradesh', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Punjab', 'Odisha', 'Assam', 'Jharkhand', 'Chhattisgarh', 'Uttarakhand', 'Himachal Pradesh', 'Jammu & Kashmir', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Nagaland', 'Arunachal Pradesh', 'Mizoram', 'Andaman & Nicobar Islands', 'India']

In [31]:
#scraping the GDP 
gdp=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[6]")
for i in gdp:
    if i.text is None :
        GDP.append("--") 
    else:
        GDP.append(i.text)
print(len(GDP),GDP)

33 ['399.921', '247.629', '240.726', '228.290', '226.806', '165.556', '143.179', '131.083', '130.791', '122.977', '118.733', '117.703', '111.519', '80.562', '79.957', '74.098', '47.982', '46.187', '45.145', '37.351', '23.690', '23.369', '11.115', '7.571', '6.397', '5.230', '5.086', '4.363', '4.233', '4.144', '3.737', '3.385', '-']

In [32]:
#scraping the GSDP_Current (18-19)
shr=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
for i in shr:
    if i.text is None :
        GSDP_Current.append("--") 
    else:
        GSDP_Current.append(i.text)
print(len(GSDP_Current),GSDP_Current)

33 ['2,632,792', '1,630,208', '1,584,764', '1,502,899', '1,493,127', '1,089,898', '942,586', '862,957', '861,031', '809,592', '781,653', '774,870', '734,163', '530,363', '526,376', '487,805', '315,881', '304,063', '297,204', '245,895', '155,956', '153,845', '73,170', '49,845', '42,114', '34,433', '33,481', '28,723', '27,870', '27,283', '24,603', '22,287', '-']

In [40]:
#scraping the GSDP_current (19-20)
shr=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[7]')
for i in shr:
    if i.text is None :
        GSDP_19_20.append("--") 
    else:
        GSDP_19_20.append(i.text)
print(len(GSDP_19_20),GSDP_19_20)

33 ['-', '1,312,929', '1,166,817', '-', '1,156,039', '793,223', '711,627', '672,018', '663,258', '561,801', '-', '634,408', '572,240', '414,977', '418,868', '396,499', '-', '243,477', '240,036', '-', '-', '124,403', '63,408', '40,583', '-', '25,093', '26,695', '20,017', '20,673', '-', '-', '18,797', '-']

In [36]:
# scraping the share (18-19)
share=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
for i in share:
    if i.text is None:
        Share.append('--')
    else:
        Share.append(i.text)

print(len(Share),Share)

33 ['13.94%', '8.63%', '8.39%', '7.96%', '7.91%', '5.77%', '4.99%', '4.57%', '4.56%', '4.29%', '4.14%', '4.10%', '3.89%', '2.81%', '2.79%', '2.58%', '1.67%', '1.61%', '1.57%', '1.30%', '0.83%', '0.81%', '0.39%', '0.26%', '0.22%', '0.18%', '0.18%', '0.15%', '0.15%', '0.14%', '0.13%', '0.12%', '-']

In [41]:
State_GDP=pd.DataFrame([])
State_GDP['Rank']=Rank[:33]
State_GDP['State']=State[:33]
State_GDP['Share In GDP']=Share[:33]
State_GDP['GDP of State']=GDP[:33]
State_GDP['GSDP_Current']=GSDP_Current[:33]
State_GDP['GSDP_19_20']=GSDP_19_20[:33]
State_GDP

,Rank,State,Share In GDP,GDP of State,GSDP_Current,GSDP_19_20
0,1,Maharashtra,13.94%,399.921,"2,632,792",-
1,2,Tamil Nadu,8.63%,247.629,"1,630,208","1,312,929"
2,3,Uttar Pradesh,8.39%,240.726,"1,584,764","1,166,817"
3,4,Gujarat,7.96%,228.290,"1,502,899",-
4,5,Karnataka,7.91%,226.806,"1,493,127","1,156,039"
5,6,West Bengal,5.77%,165.556,"1,089,898","793,223"
6,7,Rajasthan,4.99%,143.179,"942,586","711,627"
7,8,Andhra Pradesh,4.57%,131.083,"862,957","672,018"
8,9,Telangana,4.56%,130.791,"861,031","663,258"
9,10,Madhya Pradesh,4.29%,122.977,"809,592","561,801"
10,11,Kerala,4.14%,118.733,"781,653",-
11,12,Delhi,4.10%,117.703,"774,870","634,408"
12,13,Haryana,3.89%,111.519,"734,163","572,240"
13,14,Bihar,2.81%,80.562,"530,363","414,977"
14,15,Punjab,2.79%,79.957,"526,376","418,868"
15,16,Odisha,2.58%,74.098,"487,805","396,499"
16,17,Assam,1.67%,47.982,"315,881",-
17,18,Chhattisgarh,1.61%,46.187,"304,063","243,477"
18,19,Jharkhand,1.57%,45.145,"297,204","240,036"
19,20,Uttarakhand,1.30%,37.351,"245,895",-
20,21,Jammu & Kashmir,0.83%,23.690,"155,956",-
21,22,Himachal Pradesh,0.81%,23.369,"153,845","124,403"
22,23,Goa,0.39%,11.115,"73,170","63,408"
23,24,Tripura,0.26%,7.571,"49,845","40,583"
24,25,Chandigarh,0.22%,6.397,"42,114",-
25,26,Puducherry,0.18%,5.230,"34,433","25,093"
26,27,Meghalaya,0.18%,5.086,"33,481","26,695"
27,28,Sikkim,0.15%,4.363,"28,723","20,017"
28,29,Manipur,0.15%,4.233,"27,870","20,673"
29,30,Nagaland,0.14%,4.144,"27,283",-
30,31,Arunachal Pradesh,0.13%,3.737,"24,603",-
31,32,Mizoram,0.12%,3.385,"22,287","18,797"
32,33,Andaman & Nicobar Islands,-,-,-,-

In [42]:
State_GDP.to_csv("state_gdp")

### 4. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

In [58]:
url_4='https://github.com/'
driver.get(url_4)

In [59]:
repository_name =[]
repositry_descp=[]
contributer_count=[]
Language=[]

In [60]:
explore = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div[1]/div[1]/div[2]/button')       # Locating page xpath
explore.click()

In [62]:
# used to scroll to trending 

trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div[1]/div[2]/div/nav/ul/li[3]/button')
trending.click()

In [63]:
trend_open=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
trend_open.click()

In [64]:
#scraping the Repositor_Name 
rn=driver.find_elements(By.XPATH,"//span[@class='text-normal']")
for i in rn:
    if i.text is None :
        repository_name.append("--") 
    else:
        repository_name.append(i.text)
print(len(repository_name),repository_name)

25 ['deep-diver /', 'BloopAI /', 'GerevAI /', 'dair-ai /', 'mayooear /', 'mckaywrigley /', 'keijiro /', 'pelennor2170 /', 'modelscope /', 'nichtdax /', 'PlexPt /', 'cocktailpeanut /', 'Leizhenpeng /', 'josStorer /', 'hwchase17 /', 'f /', 'microsoft /', 'PlexPt /', 'mymusise /', 'lensterxyz /', 'chidiwilliams /', 'Ciphey /', 'raysan5 /', 'Beomi /', 'tloen /']

In [67]:
#scraping the Description 
des=driver.find_elements(By.XPATH,"//p[@class='col-9 color-fg-muted my-1 pr-4']")
for i in des:
    if i.text is None :
        repositry_descp.append("--") 
    else:
        repositry_descp.append(i.text)
print(len(repositry_descp),repositry_descp)

25 ['Alpaca-LoRA as Chatbot service', 'bloop is a fast code search engine written in Rust.', '🧠 ChatGPT search engine for your organization. 🔎', '🐙 Guides, papers, lecture, notebooks and resources for prompt engineering', 'GPT4 & LangChain Chatbot for large PDF docs', 'A ChatGPT clone for running locally in your browser.', 'ChatGPT integration with Unity Editor', 'A repository collecting model files for Neural Amp Modeler (NAM) all in one place', 'ModelScope: bring the notion of Model-as-a-Service to life.', 'A list of totally open alternatives to ChatGPT', 'ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。', 'The simplest way to run LLaMA on your local machine', '🎒飞书 ×（GPT-3.5 + DALL·E + Whisper）= 飞一般的工作体验 🚀 语音对话、角色扮演、多话题讨论、图片创作、表格分析、文档导出 🚀', 'Integrating ChatGPT into your browser deeply, everything you need is here', '⚡ Building applications with LLMs through composability ⚡', 'This repo includes ChatGPT prompt curation to use ChatGPT better.', 'Integrate cutting-edge LLM technology quickly and easily into your apps', 'ChatGPT Java SDK。支持 GPT3.5、 GPT4 API。开箱即用。', '一种平价的chatgpt实现方案, 基于ChatGLM-6B + LoRA', 'Lenster is a decentralized, and permissionless social media app built with Lens Protocol 🌿', "Buzz transcribes and translates audio offline on your personal computer. Powered by OpenAI's Whisper.", '⚡ Automatically decrypt encryptions without knowing the key or cipher, decode encodings, and crack hashes ⚡', 'A simple and easy-to-use library to enjoy videogames programming', 'KoAlpaca: Korean Alpaca Model based on Stanford Alpaca (feat. LLAMA and Polyglot-ko)', 'Instruct-tune LLaMA on consumer hardware']

In [70]:
#scraping the Language 
L=driver.find_elements(By.XPATH,"//span[@itemprop='programmingLanguage']")
for i in L:
    if i.text is None :
        Language.append("NAN") 
    else:
        Language.append(i.text)
print(len(Language),Language)

23 ['Python', 'TypeScript', 'Python', 'Jupyter Notebook', 'TypeScript', 'TypeScript', 'C#', 'Python', 'Python', 'CSS', 'Go', 'JavaScript', 'Python', 'HTML', 'C#', 'Java', 'Python', 'TypeScript', 'Python', 'Python', 'C', 'Jupyter Notebook', 'Jupyter Notebook']

In [73]:
contri_count=driver.find_elements(By.XPATH,'//*[@class="f6 color-fg-muted mt-2"]/a[2]')
for i in contri_count:
    if i.text is None:
        contributer_count.append('NAN')
    else:
        contributer_count.append(i.text)

print(len(contributer_count),contributer_count)

25 ['80', '86', '60', '1,190', '190', '350', '240', '12', '166', '45', '6,117', '504', '244', '183', '1,248', '5,798', '253', '255', '57', '790', '259', '772', '1,472', '61', '521']

In [76]:
Trending_Repository=pd.DataFrame([])
Trending_Repository['Name']=repository_name[:22]
Trending_Repository['Description']=repositry_descp[:22]
Trending_Repository['Language']=Language[:22]
Trending_Repository['Conutributed']=contributer_count[:22]
Trending_Repository

,Name,Description,Language,Conutributed
0,deep-diver /,Alpaca-LoRA as Chatbot service,Python,80
1,BloopAI /,bloop is a fast code search engine written in ...,TypeScript,86
2,GerevAI /,🧠 ChatGPT search engine for your organization. 🔎,Python,60
3,dair-ai /,"🐙 Guides, papers, lecture, notebooks and resou...",Jupyter Notebook,"1,190"
4,mayooear /,GPT4 & LangChain Chatbot for large PDF docs,TypeScript,190
5,mckaywrigley /,A ChatGPT clone for running locally in your br...,TypeScript,350
6,keijiro /,ChatGPT integration with Unity Editor,C#,240
7,pelennor2170 /,A repository collecting model files for Neural...,Python,12
8,modelscope /,ModelScope: bring the notion of Model-as-a-Ser...,Python,166
9,nichtdax /,A list of totally open alternatives to ChatGPT,CSS,45
10,PlexPt /,ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。,Go,"6,117"
11,cocktailpeanut /,The simplest way to run LLaMA on your local ma...,JavaScript,504
12,Leizhenpeng /,🎒飞书 ×（GPT-3.5 + DALL·E + Whisper）= 飞一般的工作体验 🚀 ...,Python,244
13,josStorer /,"Integrating ChatGPT into your browser deeply, ...",HTML,183
14,hwchase17 /,⚡ Building applications with LLMs through comp...,C#,"1,248"
15,f /,This repo includes ChatGPT prompt curation to ...,Java,"5,798"
16,microsoft /,Integrate cutting-edge LLM technology quickly ...,Python,253
17,PlexPt /,ChatGPT Java SDK。支持 GPT3.5、 GPT4 API。开箱即用。,TypeScript,255
18,mymusise /,"一种平价的chatgpt实现方案, 基于ChatGLM-6B + LoRA",Python,57
19,lensterxyz /,"Lenster is a decentralized, and permissionless...",Python,790
20,chidiwilliams /,Buzz transcribes and translates audio offline ...,C,259
21,Ciphey /,⚡ Automatically decrypt encryptions without kn...,Jupyter Notebook,772

In [77]:
Trending_Repository.to_csv("trending_github")

### 5. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [20]:
driver.get('https:/www.billboard.com/')

In [5]:
Song_Name =[]
Singer=[]
Last_Week=[]
peak_rank=[]
Weeks_on_board=[]

In [21]:
top100 = driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/header/div/div[4]/div/div/div[1]/button')       # Locating page  by xpath
top100.click()

In [23]:
chart=driver.find_element(By.XPATH,'//*[@class="a-mega-overflow-middle"]/div/div/ul/li[1]/h3/button')
chart.click()

In [16]:
chart=driver.find_element(By.XPATH,'//*[@class="a-mega-overflow-middle"]/div/div/ul/li[1]/h3/a')
chart.click()

In [28]:
hot_100=driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
hot_100.click()

In [34]:
#scraping the Rank 
rb=driver.find_elements(By.XPATH,'//*[@class="u-max-width-970 lrv-u-margin-lr-auto"]/div[2]/div /ul /li[4]/ul/li[5]')
for i in rb:
    if i.text is None :
        peak_rank.append("--") 
    else:
        peak_rank.append(i.text)
print(len(peak_rank),peak_rank)

100 ['1', '1', '2', '1', '3', '3', '1', '8', '7', '5', '11', '12', '1', '4', '1', '12', '9', '10', '7', '10', '13', '6', '22', '24', '2', '2', '23', '23', '14', '10', '11', '32', '18', '8', '29', '36', '13', '29', '11', '10', '15', '23', '43', '9', '5', '11', '25', '27', '30', '10', '40', '52', '25', '54', '55', '56', '57', '58', '52', '60', '35', '15', '29', '42', '59', '56', '32', '68', '40', '43', '42', '2', '48', '38', '53', '49', '41', '56', '79', '44', '51', '8', '17', '50', '52', '66', '63', '47', '69', '56', '91', '92', '62', '48', '73', '63', '53', '72', '87', '59']

In [36]:
#scrape the songs deatails

sng=driver.find_elements(By.XPATH,'//*[@class="u-max-width-970 lrv-u-margin-lr-auto"]/div[2]/div /ul /li[4]/ul/li[1]/h3')
for i in sng:
    if i is None:
        Song_Name('--')
    else:
        Song_Name.append(i.text)

print(len(Song_Name),Song_Name)

100 ['Flowers', 'Last Night', 'Kill Bill', 'Die For You', "Creepin'", "Boy's A Liar, Pt. 2", 'Anti-Hero', 'Calm Down', 'Thought You Should Know', 'You Proof', 'Rock And A Hard Place', 'Players', 'Unholy', "I'm Good (Blue)", 'As It Was', 'Under The Influence', "Thinkin' Bout Me", 'Just Wanna Rock', 'TQG', 'One Thing At A Time', 'Thank God', 'Cuff It', 'Escapism', 'Sure Thing', 'Lavender Haze', 'Rich Flex', 'Going, Going, Gone', 'Until I Found You', 'Everything I Love', 'Something In The Orange', "Ain't That Some", 'River', 'I Wrote The Book', 'Superhero (Heroes & Villains)', 'Snooze', 'Favorite Song', 'Red Ruby Da Sleeze', 'Heart Like A Truck', 'Shirt', 'Golden Hour', 'Man Made A Bar', 'Wait In The Truck', 'Bloody Mary', 'Bzrp Music Sessions, Vol. 53', 'Spin Bout U', 'Made You Look', 'Bebe Dame', "'98 Braves", 'Sunrise', 'Nobody Gets Me', 'Cowgirls', "What He Didn't Do", 'Painting Pictures', 'Ceilings', 'Handle On You', 'Jaded', 'Wild As Her', 'In Ha Mood', 'Special', 'Next Thing You Know', 'Whiskey Friends', 'Love You Anyway', "Devil Don't Know", 'Trance', 'Freestyle', 'Watch This (ARIZONATEARS Pluggnb Remix)', 'Born With A Beer In My Hand', 'Thousand Miles', 'Love Again', 'Dying Man', 'Dawns', 'Lift Me Up', 'Neon Star (Country Boy Lullaby)', 'Tennessee Numbers', 'Tennessee Orange', 'Tennessee Fan', "Hope That's True", 'Nonsense', 'Yandel 150', 'Keith Whitley', 'Me + All Your Reasons', 'Forever', 'Low', 'Que Vuelvas', 'I Deserve A Drink', 'AMG', "You Didn't", 'In The Bible', '10:35', 'Single Than She Was', 'Rose Colored Lenses', 'Por Las Noches', 'Heaven', 'X Si Volvemos', 'PRC', '180 (Lifestyle)', 'F150-50', 'Private Landing', "Dancin' In The Country", 'Wine Into Water']

In [37]:
#scraping singer name
sngr_name=driver.find_elements(By.XPATH,'//*[@class="u-max-width-970 lrv-u-margin-lr-auto"]/div[2]/div /ul /li[4]/ul/li[1]/span')
for i in sngr_name:
    if i is None:
        Singer('--')
    else:
        Singer.append(i.text)

print(len(Singer),Singer)

100 ['Miley Cyrus', 'Morgan Wallen', 'SZA', 'The Weeknd & Ariana Grande', 'Metro Boomin, The Weeknd & 21 Savage', 'PinkPantheress & Ice Spice', 'Taylor Swift', 'Rema & Selena Gomez', 'Morgan Wallen', 'Morgan Wallen', 'Bailey Zimmerman', 'Coi Leray', 'Sam Smith & Kim Petras', 'David Guetta & Bebe Rexha', 'Harry Styles', 'Chris Brown', 'Morgan Wallen', 'Lil Uzi Vert', 'Karol G x Shakira', 'Morgan Wallen', 'Kane Brown With Katelyn Brown', 'Beyonce', 'RAYE Featuring 070 Shake', 'Miguel', 'Taylor Swift', 'Drake & 21 Savage', 'Luke Combs', 'Stephen Sanchez', 'Morgan Wallen', 'Zach Bryan', 'Morgan Wallen', 'Miley Cyrus', 'Morgan Wallen', 'Metro Boomin, Future & Chris Brown', 'SZA', 'Toosii', 'Nicki Minaj', 'Lainey Wilson', 'SZA', 'JVKE', 'Morgan Wallen Featuring Eric Church', 'HARDY Featuring Lainey Wilson', 'Lady Gaga', 'Bizarrap & Shakira', 'Drake & 21 Savage', 'Meghan Trainor', 'Fuerza Regida X Grupo Frontera', 'Morgan Wallen', 'Morgan Wallen', 'SZA', 'Morgan Wallen Featuring ERNEST', 'Carly Pearce', 'Superstar Pride', 'Lizzy McAlpine', 'Parker McCollum', 'Miley Cyrus', 'Corey Kent', 'Ice Spice', 'Lizzo Featuring SZA', 'Jordan Davis', 'Morgan Wallen', 'Luke Combs', 'Morgan Wallen', 'Metro Boomin, Travis Scott & Young Thug', 'Lil Baby', 'Lil Uzi Vert', 'Morgan Wallen', 'Miley Cyrus Featuring Brandi Carlile', 'The Kid LAROI', 'Morgan Wallen', 'Zach Bryan Featuring Maggie Rogers', 'Rihanna', 'Morgan Wallen', 'Morgan Wallen', 'Megan Moroney', 'Morgan Wallen', 'Morgan Wallen', 'Sabrina Carpenter', 'Yandel & Feid', 'Morgan Wallen', 'Morgan Wallen', 'Lil Baby Featuring Fridayy', 'SZA', 'Carin Leon X Grupo Frontera', 'Morgan Wallen', 'Gabito Ballesteros, Peso Pluma & Natanael Cano', 'Brett Young', 'Morgan Wallen Featuring HARDY', 'Tiesto Featuring Tate McRae', 'Morgan Wallen', 'Miley Cyrus', 'Peso Pluma', 'Niall Horan', 'Karol G x Romeo Santos', 'Peso Pluma X Natanael Cano', 'Morgan Wallen', 'Morgan Wallen', 'Don Toliver Featuring Justin Bieber & Future', 'Tyler Hubbard', 'Morgan Wallen']

In [38]:
# scrapign the last week
lst_week=driver.find_elements(By.XPATH,'//*[@class="u-max-width-970 lrv-u-margin-lr-auto"]/div[2]/div /ul /li[4]/ul/li[4]')
for i in lst_week:
    if i is None:
        Last_Week('--')
    else:
        Last_Week.append(i.text)

print(len(Last_Week),Last_Week)

100 ['2', '1', '3', '4', '6', '5', '12', '19', '7', '8', '20', '24', '16', '21', '23', '26', '9', '22', '17', '10', '28', '25', '33', '37', '31', '34', '36', '39', '14', '42', '11', '-', '18', '45', '46', '67', '13', '55', '50', '49', '15', '58', '66', '70', '68', '57', '64', '27', '30', '73', '40', '79', '62', '80', '83', '-', '81', '85', '78', '84', '35', '74', '29', '94', '86', '82', '32', '-', '88', '43', '87', '98', '48', '38', '91', '54', '41', '96', '-', '44', '51', '95', '92', '90', '52', '97', '99', '47', '100', '56', '-', '-', '-', '93', '-', '63', '53', '89', '-', '59']

In [41]:
#scraping the Weeks_on_board 
wob=driver.find_elements(By.XPATH,'//*[@class="u-max-width-970 lrv-u-margin-lr-auto"]/div[2]/div /ul /li[4]/ul/li[6]')
for i in wob:
    if i.text is None :
        Weeks_on_board.append("--") 
    else:
        Weeks_on_board.append(i.text)
print(len(Weeks_on_board),Weeks_on_board)

100 ['9', '7', '14', '33', '15', '6', '21', '28', '31', '44', '40', '11', '25', '29', '50', '27', '2', '22', '3', '15', '27', '31', '15', '33', '21', '19', '18', '37', '7', '47', '2', '1', '7', '15', '14', '4', '2', '18', '20', '29', '2', '28', '11', '9', '19', '21', '12', '2', '2', '14', '2', '13', '5', '4', '11', '1', '23', '6', '5', '8', '2', '5', '2', '6', '24', '4', '2', '1', '7', '2', '7', '20', '2', '2', '14', '7', '2', '9', '5', '2', '2', '10', '14', '12', '2', '8', '10', '2', '8', '2', '1', '1', '3', '6', '5', '2', '2', '3', '4', '2']

In [43]:
Top_Song=pd.DataFrame([])
Top_Song['Peak_rank']=peak_rank
Top_Song['Song_Name']=Song_Name
Top_Song['Singer / Crew']=Singer
Top_Song['Last_Week_Rank']=Last_Week
Top_Song['Weeks_on_board']=Weeks_on_board
Top_Song

,Peak_rank,Song_Name,Singer / Crew,Last_Week_Rank,Weeks_on_board
0,1,Flowers,Miley Cyrus,2,9
1,1,Last Night,Morgan Wallen,1,7
2,2,Kill Bill,SZA,3,14
3,1,Die For You,The Weeknd & Ariana Grande,4,33
4,3,Creepin',"Metro Boomin, The Weeknd & 21 Savage",6,15
...,...,...,...,...,...
95,63,180 (Lifestyle),Morgan Wallen,63,2
96,53,F150-50,Morgan Wallen,53,2
97,72,Private Landing,Don Toliver Featuring Justin Bieber & Future,89,3
98,87,Dancin' In The Country,Tyler Hubbard,-,4
99,59,Wine Into Water,Morgan Wallen,59,2

In [44]:
Top_Song.to_csv("top_songs.billboard")

### 6. Scrape the details of Highest sellingnovels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare

    You have to find the following details:

        A) Book name

        B) Author name

        C) Volumes sold

        D) Publisher

        E) Genre

In [51]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [52]:
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [53]:
#scraping the Book_name 
bname=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]")
for i in bname:
    if i.text is None :
        Book_name.append("--") 
    else:
        Book_name.append(i.text)
print(len(Book_name),Book_name)

100 ['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [55]:
#scraping the Author_name 
Auth=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]")
for i in Auth:
    if i.text is None :
        Author_name.append("--") 
    else:
        Author_name.append(i.text)
print(len(Author_name),Author_name)

100 ['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']

In [56]:
#scraping the Genre 
gen=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]")
for i in gen:
    if i.text is None :
        Genre.append("--") 
    else:
        Genre.append(i.text)
print(len(Genre),Genre)

100 ['Crime, Thriller & Adventure', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Romance & Sagas', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Crime, Thriller & Adventure', "Children's Fiction", 'Romance & Sagas', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Romance & Sagas', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Popular Science', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Picture Books', 'Picture Books', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Humour: Collections & General', 'General & Literary Fiction', 'Autobiography: General', 'General & Literary Fiction', 'Biography: The Arts', 'Autobiography: General', 'Picture Books', 'Autobiography: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Science Fiction & Fantasy', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'Fitness & Diet', 'General & Literary Fiction', "Children's Fiction", 'Crime, Thriller & Adventure', 'Fitness & Diet', 'Young Adult Fiction', 'Usage & Writing Guides', 'Food & Drink: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Popular Culture & Media: General Interest', 'Autobiography: The Arts', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Science Fiction & Fantasy', 'Current Affairs & Issues', 'Crime, Thriller & Adventure', 'Autobiography: The Arts', 'General & Literary Fiction', 'Autobiography: The Arts', 'Travel Writing', 'Food & Drink: General', 'General & Literary Fiction', 'National & Regional Cuisine', 'Fitness & Diet', 'Travel Writing', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'Picture Books', 'General & Literary Fiction', 'Autobiography: The Arts', 'Popular Science', "Children's Annuals", 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Food & Drink: General', 'Young Adult Fiction', 'Biography: General', 'Food & Drink: General']

In [57]:
#scraping the Publisher 
pub=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]")
for i in pub:
    if i.text is None :
        Publisher.append("--") 
    else:
        Publisher.append(i.text)
print(len(Publisher),Publisher)

100 ['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']

In [58]:
#scraping the Volumes_sold 
vs=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]")
for i in vs:
    if i.text is None :
        Volumes_sold.append("--") 
    else:
        Volumes_sold.append(i.text)
print(len(Volumes_sold),Volumes_sold)

100 ['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']

In [59]:
Book=pd.DataFrame([])
Book['Book_name']=Book_name
Book['Author_name']=Author_name
Book['Genre']=Genre
Book['Publisher']=Publisher
Book['Volumes_sold']=Volumes_sold
Book

,Book_name,Author_name,Genre,Publisher,Volumes_sold
0,"Da Vinci Code,The","Brown, Dan","Crime, Thriller & Adventure",Transworld,"5,094,805"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,475,152"
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,200,654"
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,179,479"
4,Fifty Shades of Grey,"James, E. L.",Romance & Sagas,Random House,"3,758,936"
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert",General & Literary Fiction,Random House,"807,311"
96,Happy Days with the Naked Chef,"Oliver, Jamie",Food & Drink: General,Penguin,"794,201"
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",Young Adult Fiction,Scholastic Ltd.,"792,187"
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",Biography: General,Orion,"791,507"
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Food & Drink: General,Penguin,"791,095"

In [60]:
Book.to_csv("top_book_selling.csv")

### 7. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [61]:
Name=[]
Year_span=[]
Genres=[]
Run_time=[]
Ratings=[]
Votes=[]

In [62]:
driver.get(' https://www.imdb.com/list/ls095964455/')

In [63]:
#scraping the Name 
mname=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/a")
for i in mname:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

100 ['Game of Thrones', 'Stranger Things', 'The Walking Dead', '13 Reasons Why', 'The 100', 'Orange Is the New Black', 'Riverdale', "Grey's Anatomy", 'The Flash', 'Arrow', 'Money Heist', 'The Big Bang Theory', 'Black Mirror', 'Sherlock', 'Vikings', 'Pretty Little Liars', 'The Vampire Diaries', 'American Horror Story', 'Breaking Bad', 'Lucifer', 'Supernatural', 'Prison Break', 'How to Get Away with Murder', 'Teen Wolf', 'The Simpsons', 'Once Upon a Time', 'Narcos', 'Daredevil', 'Friends', 'How I Met Your Mother', 'Suits', 'Mr. Robot', 'The Originals', 'Supergirl', 'Gossip Girl', 'Sense8', 'Gotham', 'Westworld', 'Jessica Jones', 'Modern Family', 'Rick and Morty', 'Shadowhunters', 'The End of the F***ing World', 'House of Cards', 'Dark', 'Elite', 'Sex Education', 'Shameless', 'New Girl', 'Agents of S.H.I.E.L.D.', 'You', 'Dexter', 'Fear the Walking Dead', 'Family Guy', 'The Blacklist', 'Lost', 'Peaky Blinders', 'House', 'Quantico', 'Orphan Black', 'Homeland', 'Blindspot', "DC's Legends of Tomorrow", "The Handmaid's Tale", 'Chilling Adventures of Sabrina', 'The Good Doctor', 'Jane the Virgin', 'Glee', 'South Park', 'Brooklyn Nine-Nine', 'Under the Dome', 'The Umbrella Academy', 'True Detective', 'The OA', 'Desperate Housewives', 'Better Call Saul', 'Bates Motel', 'The Punisher', 'Atypical', 'Dynasty', 'This Is Us', 'The Good Place', 'Iron Fist', 'The Rain', 'Mindhunter', 'Revenge', 'Luke Cage', 'Scandal', 'The Defenders', 'Big Little Lies', 'Insatiable', 'The Mentalist', 'The Crown', 'Chernobyl', 'iZombie', 'Reign', 'A Series of Unfortunate Events', 'Criminal Minds', 'Scream: The TV Series', 'The Haunting of Hill House']

In [64]:
#scraping the Year_span 
ys=driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']")
for i in ys:
    if i.text is None :
        Year_span.append("--") 
    else:
        Year_span.append(i.text)
print(len(Year_span),Year_span)

100 ['(2011–2019)', '(2016–2024)', '(2010–2022)', '(2017–2020)', '(2014–2020)', '(2013–2019)', '(2017– )', '(2005– )', '(2014–2023)', '(2012–2020)', '(2017–2021)', '(2007–2019)', '(2011–2019)', '(2010–2017)', '(2013–2020)', '(2010–2017)', '(2009–2017)', '(2011– )', '(2008–2013)', '(2016–2021)', '(2005–2020)', '(2005–2017)', '(2014–2020)', '(2011–2017)', '(1989– )', '(2011–2018)', '(2015–2017)', '(2015–2018)', '(1994–2004)', '(2005–2014)', '(2011–2019)', '(2015–2019)', '(2013–2018)', '(2015–2021)', '(2007–2012)', '(2015–2018)', '(2014–2019)', '(2016– )', '(2015–2019)', '(2009–2020)', '(2013– )', '(2016–2019)', '(2017–2019)', '(2013–2018)', '(2017–2020)', '(2018– )', '(2019– )', '(2011–2021)', '(2011–2018)', '(2013–2020)', '(2018– )', '(2006–2013)', '(2015–2023)', '(1999– )', '(2013–2023)', '(2004–2010)', '(2013–2022)', '(2004–2012)', '(2015–2018)', '(2013–2017)', '(2011–2020)', '(2015–2020)', '(2016–2022)', '(2017– )', '(2018–2020)', '(2017– )', '(2014–2019)', '(2009–2015)', '(1997– )', '(2013–2021)', '(2013–2015)', '(2019–2023)', '(2014–2019)', '(2016–2019)', '(2004–2012)', '(2015–2022)', '(2013–2017)', '(2017–2019)', '(2017–2021)', '(2017–2022)', '(2016–2022)', '(2016–2020)', '(2017–2018)', '(2018–2020)', '(2017–2019)', '(2011–2015)', '(2016–2018)', '(2012–2018)', '(2017)', '(2017–2019)', '(2018–2019)', '(2008–2015)', '(2016–2023)', '(2019)', '(2015–2019)', '(2013–2017)', '(2017–2019)', '(2005– )', '(2015–2019)', '(2018)']

In [65]:
#scraping the Genres 
gnr=driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']/span[5]")
for i in gnr:
    if i.text is None :
        Genres.append("--") 
    else:
        Genres.append(i.text)
print(len(Genres),Genres)

100 ['Action, Adventure, Drama', 'Drama, Fantasy, Horror', 'Drama, Horror, Thriller', 'Drama, Mystery, Thriller', 'Drama, Mystery, Sci-Fi', 'Comedy, Crime, Drama', 'Crime, Drama, Mystery', 'Drama, Romance', 'Action, Adventure, Drama', 'Action, Adventure, Crime', 'Action, Crime, Drama', 'Comedy, Romance', 'Drama, Mystery, Sci-Fi', 'Crime, Drama, Mystery', 'Action, Adventure, Drama', 'Drama, Mystery, Romance', 'Drama, Fantasy, Horror', 'Drama, Horror, Sci-Fi', 'Crime, Drama, Thriller', 'Crime, Drama, Fantasy', 'Drama, Fantasy, Horror', 'Action, Crime, Drama', 'Crime, Drama, Mystery', 'Action, Drama, Fantasy', 'Animation, Comedy', 'Adventure, Fantasy, Romance', 'Biography, Crime, Drama', 'Action, Crime, Drama', 'Comedy, Romance', 'Comedy, Romance', 'Comedy, Drama', 'Crime, Drama, Thriller', 'Drama, Fantasy, Horror', 'Action, Adventure, Drama', 'Drama, Romance', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Drama, Mystery, Sci-Fi', 'Action, Crime, Drama', 'Comedy, Drama, Romance', 'Animation, Adventure, Comedy', 'Action, Drama, Fantasy', 'Adventure, Comedy, Crime', 'Drama', 'Crime, Drama, Mystery', 'Crime, Drama, Thriller', 'Comedy, Drama', 'Comedy, Drama', 'Comedy, Romance', 'Action, Adventure, Drama', 'Crime, Drama, Romance', 'Crime, Drama, Mystery', 'Drama, Horror, Sci-Fi', 'Animation, Comedy', 'Crime, Drama, Mystery', 'Adventure, Drama, Fantasy', 'Crime, Drama', 'Drama, Mystery', 'Crime, Drama, Mystery', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Action, Crime, Drama', 'Action, Adventure, Drama', 'Drama, Sci-Fi, Thriller', 'Drama, Fantasy, Horror', 'Drama', 'Comedy', 'Comedy, Drama, Music', 'Animation, Comedy', 'Comedy, Crime', 'Drama, Mystery, Sci-Fi', 'Action, Adventure, Comedy', 'Crime, Drama, Mystery', 'Drama, Fantasy, Mystery', 'Comedy, Drama, Mystery', 'Crime, Drama', 'Drama, Horror, Mystery', 'Action, Crime, Drama', 'Comedy, Drama', 'Drama', 'Comedy, Drama, Romance', 'Comedy, Drama, Fantasy', 'Action, Adventure, Crime', 'Drama, Sci-Fi, Thriller', 'Crime, Drama, Mystery', 'Drama, Mystery, Thriller', 'Action, Crime, Drama', 'Drama, Thriller', 'Action, Adventure, Crime', 'Crime, Drama, Mystery', 'Comedy, Drama, Thriller', 'Crime, Drama, Mystery', 'Biography, Drama, History', 'Drama, History, Thriller', 'Comedy, Crime, Drama', 'Drama', 'Adventure, Comedy, Drama', 'Crime, Drama, Mystery', 'Comedy, Crime, Drama', 'Drama, Horror, Mystery']

In [66]:
#scraping the Run_time 
rt=driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']/span[3]")
for i in rt:
    if i.text is None :
        Run_time.append("--") 
    else:
        Run_time.append(i.text)
print(len(Run_time),Run_time)

100 ['57 min', '51 min', '44 min', '60 min', '43 min', '59 min', '45 min', '41 min', '43 min', '42 min', '70 min', '22 min', '60 min', '88 min', '44 min', '44 min', '43 min', '60 min', '49 min', '42 min', '44 min', '44 min', '43 min', '41 min', '22 min', '60 min', '49 min', '54 min', '22 min', '22 min', '44 min', '49 min', '45 min', '43 min', '42 min', '60 min', '42 min', '62 min', '56 min', '22 min', '23 min', '42 min', '25 min', '51 min', '60 min', '60 min', '45 min', '46 min', '22 min', '45 min', '45 min', '53 min', '44 min', '22 min', '43 min', '44 min', '60 min', '44 min', '42 min', '44 min', '55 min', '42 min', '42 min', '60 min', '60 min', '41 min', '60 min', '44 min', '22 min', '22 min', '43 min', '60 min', '55 min', '60 min', '45 min', '46 min', '45 min', '53 min', '30 min', '42 min', '45 min', '22 min', '55 min', '45 min', '60 min', '44 min', '55 min', '43 min', '50 min', '60 min', '45 min', '43 min', '58 min', '330 min', '42 min', '42 min', '50 min', '42 min', '45 min', '572 min']

In [67]:
#scraping the Ratings 
rate=driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]")
for i in rate:
    if i.text is None :
        Ratings.append("--") 
    else:
        Ratings.append(i.text)
print(len(Ratings),Ratings)

100 ['9.2', '8.7', '8.1', '7.5', '7.6', '8.1', '6.6', '7.6', '7.5', '7.5', '8.2', '8.2', '8.8', '9.1', '8.5', '7.4', '7.7', '8', '9.5', '8.1', '8.4', '8.3', '8.1', '7.7', '8.7', '7.7', '8.8', '8.6', '8.9', '8.3', '8.5', '8.5', '8.3', '6.2', '7.5', '8.2', '7.8', '8.5', '7.9', '8.5', '9.1', '6.5', '8', '8.7', '8.7', '7.3', '8.3', '8.6', '7.8', '7.5', '7.7', '8.7', '6.8', '8.2', '8', '8.3', '8.8', '8.7', '6.7', '8.3', '8.3', '7.3', '6.8', '8.4', '7.4', '8.1', '7.9', '6.8', '8.7', '8.4', '6.5', '7.9', '8.9', '7.8', '7.6', '8.9', '8.1', '8.5', '8.2', '7.3', '8.7', '8.2', '6.4', '6.3', '8.6', '7.8', '7.3', '7.7', '7.2', '8.5', '6.5', '8.1', '8.6', '9.4', '7.8', '7.4', '7.8', '8.1', '7.1', '8.6']

In [68]:
#scraping the Votes 
v=driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[4]/span[2]")
for i in v:
    if i.text is None :
        Votes.append("--") 
    else:
        Votes.append(i.text)
print(len(Votes),Votes)

100 ['2,140,943', '1,225,349', '1,016,409', '299,339', '258,192', '307,404', '147,375', '317,322', '352,636', '435,662', '489,778', '822,316', '562,879', '942,212', '545,710', '170,720', '328,362', '324,908', '1,945,283', '332,288', '454,420', '546,501', '155,864', '154,200', '414,288', '228,048', '434,557', '448,954', '1,015,721', '695,180', '419,974', '394,978', '139,356', '125,823', '179,203', '156,928', '233,472', '512,604', '217,942', '442,677', '542,941', '65,773', '199,038', '511,089', '403,000', '82,821', '293,832', '249,929', '230,677', '219,566', '268,470', '734,313', '133,216', '347,486', '256,545', '562,763', '570,691', '473,976', '61,791', '112,706', '346,948', '75,625', '106,630', '244,623', '99,118', '99,185', '53,106', '150,714', '380,689', '327,153', '108,207', '255,109', '585,813', '107,385', '131,785', '558,376', '110,558', '243,870', '93,507', '23,464', '147,972', '167,925', '133,845', '38,666', '300,054', '121,574', '133,899', '75,645', '110,568', '206,429', '30,038', '189,110', '227,418', '783,603', '70,165', '51,077', '63,096', '205,291', '42,571', '254,058']

In [69]:
TV_Series=pd.DataFrame([])
TV_Series['Name']=Name
TV_Series['Year_span']=Year_span
TV_Series['Run_time']=Run_time
TV_Series['Genres']=Genres
TV_Series['Ratings']=Ratings
TV_Series['Votes']=Votes
TV_Series

,Name,Year_span,Run_time,Genres,Ratings,Votes
0,Game of Thrones,(2011–2019),57 min,"Action, Adventure, Drama",9.2,"2,140,943"
1,Stranger Things,(2016–2024),51 min,"Drama, Fantasy, Horror",8.7,"1,225,349"
2,The Walking Dead,(2010–2022),44 min,"Drama, Horror, Thriller",8.1,"1,016,409"
3,13 Reasons Why,(2017–2020),60 min,"Drama, Mystery, Thriller",7.5,"299,339"
4,The 100,(2014–2020),43 min,"Drama, Mystery, Sci-Fi",7.6,"258,192"
...,...,...,...,...,...,...
95,Reign,(2013–2017),42 min,Drama,7.4,"51,077"
96,A Series of Unfortunate Events,(2017–2019),50 min,"Adventure, Comedy, Drama",7.8,"63,096"
97,Criminal Minds,(2005– ),42 min,"Crime, Drama, Mystery",8.1,"205,291"
98,Scream: The TV Series,(2015–2019),45 min,"Comedy, Crime, Drama",7.1,"42,571"
99,The Haunting of Hill House,(2018),572 min,"Drama, Horror, Mystery",8.6,"254,058"

In [71]:
TV_Series.to_csv("tv_series.csv")

### 8. Details of Datasetsfrom UCI machine learning repositories.
Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [72]:
driver.get(' https://archive.ics.uci.edu/')

In [73]:
Dataset_Name=[]
Data_Type=[]
Task=[]
Attribute_Type=[]
No_of_Instances=[]
No_of_Attribute=[]
Year=[]

In [75]:
search_1 = driver.find_element(By.XPATH,'/html/body/table[1]/tbody/tr/td[2]/span[2]/a')       # Locating page foe top videos by xpath
search_1.click()

In [76]:
#scraping the Dataset_Name 
dname=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
for i in dname:
    if i.text is None :
        Dataset_Name.append("--") 
    else:
        Dataset_Name.append(i.text)
print(len(Dataset_Name),Dataset_Name)

622 ['Abalone', 'Adult', 'Annealing', 'Anonymous Microsoft Web Data', 'Arrhythmia', 'Artificial Characters', 'Audiology (Original)', 'Audiology (Standardized)', 'Auto MPG', 'Automobile', 'Badges', 'Balance Scale', 'Balloons', 'Breast Cancer', 'Breast Cancer Wisconsin (Original)', 'Breast Cancer Wisconsin (Prognostic)', 'Breast Cancer Wisconsin (Diagnostic)', 'Pittsburgh Bridges', 'Car Evaluation', 'Census Income', 'Chess (King-Rook vs. King-Knight)', 'Chess (King-Rook vs. King-Pawn)', 'Chess (King-Rook vs. King)', 'Chess (Domain Theories)', 'Bach Chorales', 'Connect-4', 'Credit Approval', 'Japanese Credit Screening', 'Computer Hardware', 'Contraceptive Method Choice', 'Covertype', 'Cylinder Bands', 'Dermatology', 'Diabetes', 'DGP2 - The Second Data Generation Program', 'Document Understanding', 'EBL Domain Theories', 'Echocardiogram', 'Ecoli', 'Flags', 'Function Finding', 'Glass Identification', "Haberman's Survival", 'Hayes-Roth', 'Heart Disease', 'Hepatitis', 'Horse Colic', 'ICU', 'Image Segmentation', 'Internet Advertisements', 'Ionosphere', 'Iris', 'ISOLET', 'Kinship', 'Labor Relations', 'LED Display Domain', 'Lenses', 'Letter Recognition', 'Liver Disorders', 'Logic Theorist', 'Lung Cancer', 'Lymphography', 'Mechanical Analysis', 'Meta-data', 'Mobile Robots', 'Molecular Biology (Promoter Gene Sequences)', 'Molecular Biology (Protein Secondary Structure)', 'Molecular Biology (Splice-junction Gene Sequences)', "MONK's Problems", 'Moral Reasoner', 'Multiple Features', 'Mushroom', 'Musk (Version 1)', 'Musk (Version 2)', 'Nursery', 'Othello Domain Theory', 'Page Blocks Classification', 'Optical Recognition of Handwritten Digits', 'Pen-Based Recognition of Handwritten Digits', 'Post-Operative Patient', 'Primary Tumor', 'Prodigy', 'Qualitative Structure Activity Relationships', 'Quadruped Mammals', 'Servo', 'Shuttle Landing Control', 'Solar Flare', 'Soybean (Large)', 'Soybean (Small)', 'Challenger USA Space Shuttle O-Ring', 'Low Resolution Spectrometer', 'Spambase', 'SPECT Heart', 'SPECTF Heart', 'Sponge', 'Statlog Project', 'Student Loan Relational', 'Teaching Assistant Evaluation', 'Tic-Tac-Toe Endgame', 'Thyroid Disease', 'Trains', 'University', 'Congressional Voting Records', 'Water Treatment Plant', 'Waveform Database Generator (Version 1)', 'Waveform Database Generator (Version 2)', 'Wine', 'Yeast', 'Zoo', 'Undocumented', 'Twenty Newsgroups', 'Australian Sign Language signs', 'Australian Sign Language signs (High Quality)', 'US Census Data (1990)', 'Census-Income (KDD)', 'Coil 1999 Competition Data', 'Corel Image Features', 'E. Coli Genes', 'EEG Database', 'El Nino', 'Entree Chicago Recommendation Data', 'CMU Face Images', 'Insurance Company Benchmark (COIL 2000)', 'Internet Usage Data', 'IPUMS Census Database', 'Japanese Vowels', 'KDD Cup 1998 Data', 'KDD Cup 1999 Data', 'M. Tuberculosis Genes', 'Movie', 'MSNBC.com Anonymous Web Data', 'NSF Research Award Abstracts 1990-2003', 'Pioneer-1 Mobile Robot Data', 'Pseudo Periodic Synthetic Time Series', 'Reuters-21578 Text Categorization Collection', 'Robot Execution Failures', 'Synthetic Control Chart Time Series', 'Syskill and Webert Web Page Ratings', 'UNIX User Data', 'Volcanoes on Venus - JARtool experiment', 'Statlog (Australian Credit Approval)', 'Statlog (German Credit Data)', 'Statlog (Heart)', 'Statlog (Landsat Satellite)', 'Statlog (Image Segmentation)', 'Statlog (Shuttle)', 'Statlog (Vehicle Silhouettes)', 'Connectionist Bench (Nettalk Corpus)', 'Connectionist Bench (Sonar, Mines vs. Rocks)', 'Connectionist Bench (Vowel Recognition - Deterding Data)', 'Economic Sanctions', 'Protein Data', 'Cloud', 'CalIt2 Building People Counts', 'Dodgers Loop Sensor', 'Poker Hand', 'MAGIC Gamma Telescope', 'UJI Pen Characters', 'Mammographic Mass', 'Forest Fires', 'Reuters Transcribed Subset', 'Bag of Words', 'Concrete Compressive Strength', 'Hill-Valley', 'Arcene', 'Dexter', 'Dorothea', 'Gisette', 'Madelon', 'Ozone Level Detection', 'Abscisic Acid Signaling Network', 'Parkinsons', 'Character Trajectories', 'Blood Transfusion Service Center', 'UJI Pen Characters (Version 2)', 'Semeion Handwritten Digit', 'SECOM', 'Plants', 'Libras Movement', 'Concrete Slump Test', 'Communities and Crime', 'Acute Inflammations', 'Wine Quality', 'URL Reputation', 'p53 Mutants', 'Parkinsons Telemonitoring', 'Demospongiae', 'Opinosis Opinion ⁄ Review', 'Breast Tissue', 'Cardiotocography', 'Wall-Following Robot Navigation Data', 'Spoken Arabic Digit', 'Localization Data for Person Activity', 'AutoUniv', 'Steel Plates Faults', 'MiniBooNE particle identification', 'YearPredictionMSD', 'PEMS-SF', 'OpinRank Review Dataset', 'Relative location of CT slices on axial axis', 'Online Handwritten Assamese Characters Dataset', 'PubChem Bioassay Data', 'Record Linkage Comparison Patterns', 'Communities and Crime Unnormalized', 'Vertebral Column', 'EMG Physical Action Data Set', 'Vicon Physical Action Data Set', 'Amazon Commerce reviews set', 'Amazon Access Samples', 'Reuter_50_50', 'Farm Ads', 'DBWorld e-mails', 'KEGG Metabolic Relation Network (Directed)', 'KEGG Metabolic Reaction Network (Undirected)', 'Bank Marketing', 'YouTube Comedy Slam Preference Data', 'Gas Sensor Array Drift Dataset', 'ILPD (Indian Liver Patient Dataset)', 'OPPORTUNITY Activity Recognition', 'Nomao', 'SMS Spam Collection', 'Skin Segmentation', 'Planning Relax', 'PAMAP2 Physical Activity Monitoring', 'Restaurant & consumer data', 'CNAE-9', 'Individual household electric power consumption', 'seeds', 'Northix', 'QtyT40I10D100K', 'Legal Case Reports', 'Human Activity Recognition Using Smartphones', 'One-hundred plant species leaves data set', 'Energy efficiency', 'Yacht Hydrodynamics', 'Fertility', 'Daphnet Freezing of Gait', '3D Road Network (North Jutland, Denmark)', 'ISTANBUL STOCK EXCHANGE', 'Buzz in social media', 'First-order theorem proving', 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)', 'Gas sensor arrays in open sampling settings', 'Climate Model Simulation Crashes', 'MicroMass', 'QSAR biodegradation', 'BLOGGER', 'Daily and Sports Activities', 'User Knowledge Modeling', 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection', 'NYSK', 'Turkiye Student Evaluation', "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)", 'EEG Eye State', 'Physicochemical Properties of Protein Tertiary Structure', 'seismic-bumps', 'banknote authentication', 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat', 'YouTube Multiview Video Games Dataset', 'Gas Sensor Array Drift Dataset at Different Concentrations', 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors', 'SkillCraft1 Master Table Dataset', 'Weight Lifting Exercises monitored with Inertial Measurement Units', 'SML2010', 'Bike Sharing Dataset', 'Predict keywords activities in a online social media', 'Thoracic Surgery Data', 'EMG dataset in Lower Limb', 'SUSY', 'HIGGS', 'Qualitative_Bankruptcy', 'LSVT Voice Rehabilitation', 'Dataset for ADL Recognition with Wrist-worn Accelerometer', 'Wilt', 'User Identification From Walking Activity', 'Activity Recognition from Single Chest-Mounted Accelerometer', 'Leaf', 'Dresses_Attribute_Sales', 'Tamilnadu Electricity Board Hourly Readings', 'Airfoil Self-Noise', 'Wholesale customers', 'Twitter Data set for Arabic Sentiment Analysis', 'Combined Cycle Power Plant', 'Urban Land Cover', 'Diabetes 130-US hospitals for years 1999-2008', 'Bach Choral Harmony', 'StoneFlakes', 'Tennis Major Tournament Match Statistics', 'Parkinson Speech Dataset with Multiple Types of Sound Recordings', 'Gesture Phase Segmentation', 'Perfume Data', 'BlogFeedback', 'REALDISP Activity Recognition Dataset', 'Newspaper and magazine images segmentation dataset', 'AAAI 2014 Accepted Papers', 'Gas sensor array under flow modulation', 'Gas sensor array exposed to turbulent gas mixtures', 'UJIIndoorLoc', 'Sentence Classification', 'Dow Jones Index', 'sEMG for Basic Hand movements', 'AAAI 2013 Accepted Papers', 'Geographical Original of Music', 'Condition Based Maintenance of Naval Propulsion Plants', 'Grammatical Facial Expressions', 'NoisyOffice', 'MHEALTH Dataset', 'Student Performance', 'ElectricityLoadDiagrams20112014', 'Gas sensor array under dynamic gas mixtures', 'microblogPCU', 'Firm-Teacher_Clave-Direction_Classification', 'Dataset for Sensorless Drive Diagnosis', 'TV News Channel Commercial Detection Dataset', 'Phishing Websites', 'Greenhouse Gas Observing Network', 'Diabetic Retinopathy Debrecen Data Set', 'HIV-1 protease cleavage', 'Sentiment Labelled Sentences', 'Online News Popularity', 'Forest type mapping', 'wiki4HE', 'Online Video Characteristics and Transcoding Time Dataset', 'Chronic_Kidney_Disease', 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014', 'Folio', 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015', 'Cuff-Less Blood Pressure Estimation', 'Smartphone-Based Recognition of Human Activities and Postural Transitions', 'Mice Protein Expression', 'UJIIndoorLoc-Mag', 'Heterogeneity Activity Recognition', 'Educational Process Mining (EPM): A Learning Analytics Data Set', 'HEPMASS', 'Indoor User Movement Prediction from RSS data', 'Open University Learning Analytics dataset', 'default of credit card clients', 'Mesothelioma’s disease data set', 'Online Retail', 'SIFT10M', 'GPS Trajectories', 'Detect Malacious Executable(AntiVirus)', 'Occupancy Detection', 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease', 'News Aggregator', 'Air Quality', 'Twin gas sensor arrays', 'Gas sensors for home activity monitoring', 'Facebook Comment Volume Dataset', 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)', 'Polish companies bankruptcy data', 'Activity Recognition system based on Multisensor data fusion (AReM)', 'Dota2 Games Results', 'Facebook metrics', 'UbiqLog (smartphone lifelogging)', 'NIPS Conference Papers 1987-2015', 'HTRU2', 'Drug consumption (quantified)', 'Appliances energy prediction', 'Miskolc IIS Hybrid IPS', 'KDC-4007 dataset Collection', 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone', 'DrivFace', 'Website Phishing', 'YouTube Spam Collection', 'Beijing PM2.5 Data', 'Cargo 2000 Freight Tracking and Tracing', 'Cervical cancer (Risk Factors)', 'Quality Assessment of Digital Colposcopies', 'KASANDR', 'FMA: A Dataset For Music Analysis', 'Air quality', 'Epileptic Seizure Recognition', 'Devanagari Handwritten Character Dataset', 'Stock portfolio performance', 'MoCap Hand Postures', 'Early biomarkers of Parkinson�s disease based on natural connected speech', 'Data for Software Engineering Teamwork Assessment in Education Setting', 'PM2.5 Data of Five Chinese Cities', 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet', 'Sales_Transactions_Dataset_Weekly', 'Las Vegas Strip', 'Eco-hotel', 'MEU-Mobile KSD', 'Crowdsourced Mapping', 'gene expression cancer RNA-Seq', 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer', 'chestnut – LARVIC', 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network', 'Motion Capture Hand Postures', 'Anuran Calls (MFCCs)', 'TTC-3600: Benchmark dataset for Turkish text categorization', 'Gastrointestinal Lesions in Regular Colonoscopy', 'Daily Demand Forecasting Orders', 'Paper Reviews', 'extention of Z-Alizadeh sani dataset', 'Z-Alizadeh Sani', 'Dynamic Features of VirusShare Executables', 'IDA2016Challenge', 'DSRC Vehicle Communications', 'Mturk User-Perceived Clusters over Images', 'Character Font Images', 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels', 'Autistic Spectrum Disorder Screening Data for Children', 'Autistic Spectrum Disorder Screening Data for Adolescent', 'APS Failure at Scania Trucks', 'Wireless Indoor Localization', 'HCC Survival', 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015', 'University of Tehran Question Dataset 2016 (UTQD.2016)', 'Autism Screening Adult', 'Activity recognition with healthy older people using a batteryless wearable sensor', 'Immunotherapy Dataset', 'Cryotherapy Dataset', 'OCT data & Color Fundus Images of Left & Right Eyes', 'Discrete Tone Image Dataset', 'News Popularity in Multiple Social Media Platforms', 'Ultrasonic flowmeter diagnostics', 'ICMLA 2014 Accepted Papers Data Set', 'BLE RSSI Dataset for Indoor localization and Navigation', 'Container Crane Controller Data Set', 'Residential Building Data Set', 'Health News in Twitter', 'chipseq', 'SGEMM GPU kernel performance', 'Repeat Consumption Matrices', 'detection_of_IoT_botnet_attacks_N_BaIoT', 'Absenteeism at work', 'SCADI', 'Condition monitoring of hydraulic systems', 'Carbon Nanotubes', 'Optical Interconnection Network', 'Sports articles for objectivity analysis', 'Breast Cancer Coimbra', 'GNFUV Unmanned Surface Vehicles Sensor Data', 'Dishonest Internet users Dataset', 'Victorian Era Authorship Attribution', 'Simulated Falls and Daily Living Activities Data Set', 'Multimodal Damage Identification for Humanitarian Computing', 'EEG Steady-State Visual Evoked Potential Signals', 'Roman Urdu Data Set', 'Avila', 'PANDOR', 'Drug Review Dataset (Druglib.com)', 'Drug Review Dataset (Drugs.com)', 'Physical Unclonable Functions', 'Superconductivty Data', 'WESAD (Wearable Stress and Affect Detection)', 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2', 'Student Academics Performance', 'Online Shoppers Purchasing Intention Dataset', 'PMU-UD', "Parkinson's Disease Classification", 'Electrical Grid Stability Simulated Data', 'Caesarian Section Classification Dataset', 'BAUM-1', 'BAUM-2', 'Audit Data', 'BuddyMove Data Set', 'Real estate valuation data set', 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set', 'Somerville Happiness Survey', '2.4 GHZ Indoor Channel Measurements', 'EMG data for gestures', 'Parking Birmingham', 'Behavior of the urban traffic of the city of Sao Paulo in Brazil', 'Travel Reviews', 'Tarvel Review Ratings', 'Rice Leaf Diseases', 'Gas sensor array temperature modulation', 'Facebook Live Sellers in Thailand', 'Parkinson Dataset with replicated acoustic features', 'Metro Interstate Traffic Volume', 'Query Analytics Workloads Dataset', 'Wave Energy Converters', 'PPG-DaLiA', 'Alcohol QCM Sensor Dataset', 'Divorce Predictors data set', 'Incident management process enriched event log', 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)', 'MEx', 'Beijing Multi-Site Air-Quality Data', 'Online Retail II', 'Hepatitis C Virus (HCV) for Egyptian patients', 'QSAR fish toxicity', 'QSAR aquatic toxicity', 'Human Activity Recognition from Continuous Ambient Sensor Data', 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset', 'QSAR oral toxicity', 'QSAR androgen receptor', 'QSAR Bioconcentration classes dataset', 'QSAR fish bioconcentration factor (BCF)', 'A study of Asian Religious and Biblical Texts', 'Real-time Election Results: Portugal 2019', 'Bias correction of numerical prediction model temperature forecast', 'Bar Crawl: Detecting Heavy Drinking', 'Kitsune Network Attack Dataset', 'Shoulder Implant X-Ray Manufacturer Classification', 'Speaker Accent Recognition', 'Heart failure clinical records', 'Deepfakes: Medical Image Tamper Detection', 'selfBACK', 'South German Credit', 'Exasens', 'Swarm Behaviour', 'Crop mapping using fused optical-radar data set', 'BitcoinHeistRansomwareAddressDataset', 'Facebook Large Page-Page Network', 'Amphibians', 'Early stage diabetes risk prediction dataset.', 'Turkish Spam V01', 'Stock keeping units', 'Demand Forecasting for a store', 'Detect Malware Types', 'Wave Energy Converters', 'Youtube cookery channels viewers comments in Hinglish', 'Pedestrian in Traffic Dataset', 'Cervical Cancer Behavior Risk', 'Sattriya_Dance_Single_Hand_Gestures Dataset', 'Divorce Predictors data set', '3W dataset', 'Malware static and dynamic features VxHeaven and Virus Total', 'Internet Firewall Data', 'User Profiling and Abusive Language Detection Dataset', 'Estimation of obesity levels based on eating habits and physical condition', 'Rice (Cammeo and Osmancik)', 'Vehicle routing and scheduling problems', 'Algerian Forest Fires Dataset', 'Breath Metabolomics', 'Horton General Hospital', 'UrbanGB, urban road accidents coordinates labelled by the urban center', 'Gas Turbine CO and NOx Emission Data Set', 'Activity recognition using wearable physiological measurements', 'clickstream data for online shopping', 'CNNpred: CNN-based stock market prediction using a diverse set of variables', 'Apartment for rent classified', ': Simulated Data set of Iraqi tourism places', 'Nasarian CAD Dataset', 'Monolithic Columns in Troad and Mysia Region', 'Bar Crawl: Detecting Heavy Drinking', 'Seoul Bike Sharing Demand', 'Person Classification Gait Data', 'Shill Bidding Dataset', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Bone marrow transplant: children', 'Exasens', 'COVID-19 Surveillance', 'Refractive errors', 'Shoulder Implant X-Ray Manufacturer Classification', 'CLINC150', 'HCV data', 'Taiwanese Bankruptcy Prediction', 'South German Credit (UPDATE)', 'IIWA14-R820-Gazebo-Dataset-10Trajectories', 'Guitar Chords finger positions', 'Russian Corpus of Biographical Texts', 'Codon usage', 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset', 'Myocardial infarction complications', 'Hungarian Chickenpox Cases', 'Simulated data for survival modelling', 'Student Performance on an entrance examination', 'Chemical Composition of Ceramic Samples', 'Labeled Text Forum Threads Dataset', 'Stock keeping units', 'BLE RSSI dataset for Indoor localization', 'Basketball dataset', 'GitHub MUSAE', 'Anticancer peptides', 'Monolithic Columns in Troad and Mysia Region', 'Gender by Name', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Shoulder Implant Manufacture Classification', 'LastFM Asia Social Network', 'Wheat kernels', 'Productivity Prediction of Garment Employees', 'Multi-view Brain Networks', 'LastFM Asia Social Network', 'Wisesight Sentiment Corpus', 'AI4I 2020 Predictive Maintenance Dataset', 'Dry Bean Dataset', 'in-vehicle coupon recommendation', 'Gait Classification', 'Wikipedia Math Essentials', 'Wikipedia Math Essentials', 'Synchronous Machine Data Set', 'Average Localization Error (ALE) in sensor node localization process in WSNs', '9mers from cullpdb', 'TamilSentiMix', 'Accelerometer', 'Synchronous Machine Data Set', 'Pedal Me Bicycle Deliveries', 'Turkish Headlines Dataset', 'Secondary Mushroom Dataset', 'Power consumption of Tetouan city', 'Raisin Dataset', 'Steel Industry Energy Consumption Dataset', 'Gender Gap in Spanish WP', 'Non verbal tourists data', 'Roman Urdu Sentiment Analysis Dataset (RUSAD)', 'TUANDROMD ( Tezpur University Android Malware Dataset)', 'Higher Education Students Performance Evaluation Dataset', 'Risk Factor prediction of Chronic Kidney Disease', 'Lab Test', 'Shoulder Implant Manufacture Classification', 'Rocket League Skillshots Data Set', 'Sepsis survival minimal clinical records', 'Water Quality Prediction', 'Traffic Flow Forecasting', 'sentiment analysis in Saudi Arabia about distance education during Covid-19', 'Kain Tradisional Sambas', 'Image Recognition Task Execution Times in Mobile Edge Computing', 'REWEMA', 'REJAFADA', 'Steel Industry Energy Consumption Dataset', 'Influenza outbreak event prediction via Twitter data', 'Turkish Music Emotion Dataset', 'Maternal Health Risk Data Set', 'Room Occupancy Estimation', 'Image Recognition Task Execution Times in Mobile Edge Computing']

In [77]:
#scraping the Data_Type 
dtype=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
for i in dtype:
    if i.text is None :
        Data_Type.append("--") 
    else:
        Data_Type.append(i.text)
print(len(Data_Type),Data_Type)

623 ['Data Types', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Univariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Univariate, Time-Series ', 'Multivariate, Spatial ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Data-Generator ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Sequential, Domain-Theory ', 'Sequential ', 'Sequential, Domain-Theory ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Domain-Theory ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Time-Series ', 'Spatio-temporal ', 'Transactional, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Relational ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', 'Univariate, Time-Series ', 'Text ', 'Multivariate, Time-Series ', 'Time-Series ', 'Multivariate, Text ', 'Text, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Text ', 'Text ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Domain-Theory ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate, Text, Domain-Theory ', 'Time-Series, Domain-Theory ', 'Multivariate, Text, Domain-Theory ', 'Text ', 'Text ', 'Multivariate, Univariate, Text ', 'Multivariate, Univariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate, Text, Domain-Theory ', 'Univariate ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate, Text ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Sequential, Text ', 'Multivariate, Univariate, Time-Series ', 'Time-Series, Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Text ', 'Univariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Univariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series, Domain-Theory ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Time-Series ', 'Text ', ' ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Sequential, Text ', 'Multivariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', ' ', 'Sequential ', 'Univariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Text ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Time-Series ', 'Multivariate, Univariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Sequential ', 'Text ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Univariate ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Text ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Sequential, Time-Series ', 'Time-Series ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Sequential ', ' ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Text ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Univariate ']

In [78]:
#scraping the Task 
t=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
for i in t:
    if i.text is None :
        Task.append("--") 
    else:
        Task.append(i.text)
print(len(Task),Task)

623 ['Default Task', 'Classification ', 'Classification ', 'Classification ', 'Recommender-Systems ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Function-Learning ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Relational-Learning ', ' ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Recommender-Systems ', 'Classification ', 'Regression, Description ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', ' ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Regression, Clustering ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering ', 'Classification, Regression ', 'Regression, Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering, Causa ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Regression ', ' ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression, Clustering ', 'Classification, Regression ', 'Classification, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification, Regression, Clustering ', 'Clustering ', 'Classification, Regression ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Clustering ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Recommendation ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Regression, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Causal-Discovery ', 'Clustering ', 'Regression, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ']

In [79]:
#scraping the Attribute_Type 
att=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
for i in att:
    if i.text is None :
        Attribute_Type.append("--") 
    else:
        Attribute_Type.append(i.text)
print(len(Attribute_Type),Attribute_Type)

623 ['Attribute Types', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical, Real ', 'Categorical, Integer, Real ', ' ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Real ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Real, Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', ' ', ' ', 'Categorical, Integer, Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Real ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Integer ', 'Categorical, Integer, Real ', ' ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', ' ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Integer ', 'Categorical ', ' ', 'Integer, Real ', 'Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Real ', 'Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Real ', 'Real ', ' ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical ', ' ', 'Categorical, Real ', ' ', 'Categorical ', 'Integer ', 'Real ', 'Categorical ', ' ', ' ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Categorical ', 'Real ', 'Real ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Integer ', 'Integer ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Categorical ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', ' ', 'Integer ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Categorical ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', 'Integer, Real ', ' ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Integer ', 'Integer ', 'Integer ', ' ', 'Real ', 'Categorical ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', ' ', 'Integer, Real ', 'Real ', 'Integer ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Integer ', ' ', 'Real ', ' ', 'Real ', 'Integer ', ' ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', ' ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', ' ', ' ', 'Real ', ' ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', 'Real ', 'Real ']

In [80]:
#scraping the No_of_Instances 
noi=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
for i in noi:
    if i.text is None :
        No_of_Instances.append("--") 
    else:
        No_of_Instances.append(i.text)
print(len(No_of_Instances),No_of_Instances)

623 ['# Instances', '4177 ', '48842 ', '798 ', '37711 ', '452 ', '6000 ', '226 ', '226 ', '398 ', '205 ', '294 ', '625 ', '16 ', '286 ', '699 ', '198 ', '569 ', '108 ', '1728 ', '48842 ', ' ', '3196 ', '28056 ', ' ', '100 ', '67557 ', '690 ', '125 ', '209 ', '1473 ', '581012 ', '512 ', '366 ', ' ', ' ', ' ', ' ', '132 ', '336 ', '194 ', '352 ', '214 ', '306 ', '160 ', '303 ', '155 ', '368 ', ' ', '2310 ', '3279 ', '351 ', '150 ', '7797 ', '104 ', '57 ', ' ', '24 ', '20000 ', '345 ', ' ', '32 ', '148 ', '209 ', '528 ', ' ', '106 ', '128 ', '3190 ', '432 ', '202 ', '2000 ', '8124 ', '476 ', '6598 ', '12960 ', ' ', '5473 ', '5620 ', '10992 ', '90 ', '339 ', ' ', ' ', ' ', '167 ', '15 ', '1389 ', '307 ', '47 ', '23 ', '531 ', '4601 ', '267 ', '267 ', '76 ', ' ', '1000 ', '151 ', '958 ', '7200 ', '10 ', '285 ', '435 ', '527 ', '5000 ', '5000 ', '178 ', '1484 ', '101 ', ' ', '20000 ', '6650 ', '2565 ', '2458285 ', '299285 ', '340 ', '68040 ', ' ', '122 ', '178080 ', '50672 ', '640 ', '9000 ', '10104 ', '256932 ', '640 ', '191779 ', '4000000 ', ' ', '10000 ', '989818 ', '129000 ', ' ', '100000 ', '21578 ', '463 ', '600 ', '332 ', ' ', ' ', '690 ', '1000 ', '270 ', '6435 ', '2310 ', '58000 ', '946 ', '20008 ', '208 ', '528 ', ' ', ' ', '1024 ', '10080 ', '50400 ', '1025010 ', '19020 ', '1364 ', '961 ', '517 ', '200 ', '8000000 ', '1030 ', '606 ', '900 ', '2600 ', '1950 ', '13500 ', '4400 ', '2536 ', '300 ', '197 ', '2858 ', '748 ', '11640 ', '1593 ', '1567 ', '22632 ', '360 ', '103 ', '1994 ', '120 ', '4898 ', '2396130 ', '16772 ', '5875 ', '503 ', '51 ', '106 ', '2126 ', '5456 ', '8800 ', '164860 ', ' ', '1941 ', '130065 ', '515345 ', '440 ', ' ', '53500 ', '8235 ', ' ', '5749132 ', '2215 ', '310 ', '10000 ', '3000 ', '1500 ', '30000 ', '2500 ', '4143 ', '64 ', '53414 ', '65554 ', '45211 ', '1138562 ', '13910 ', '583 ', '2551 ', '34465 ', '5574 ', '245057 ', '182 ', '3850505 ', '138 ', '1080 ', '2075259 ', '210 ', '115 ', '3960456 ', ' ', '10299 ', '1600 ', '768 ', '308 ', '100 ', '237 ', '434874 ', '536 ', '140000 ', '6118 ', '165632 ', '18000 ', '540 ', '931 ', '1055 ', '100 ', '9120 ', '403 ', '111740 ', '10421 ', '5820 ', '403 ', '14980 ', '45730 ', '2584 ', '1372 ', '306 ', '120000 ', '13910 ', '2747 ', '3395 ', '39242 ', '4137 ', '17389 ', '51 ', '470 ', '132 ', '5000000 ', '11000000 ', '250 ', '126 ', ' ', '4889 ', ' ', ' ', '340 ', '501 ', '45781 ', '1503 ', '440 ', '2000 ', '9568 ', '168 ', '100000 ', '5665 ', '79 ', '127 ', '1040 ', '9900 ', '560 ', '60021 ', '1419 ', '101 ', '399 ', '58 ', '180 ', '21048 ', ' ', '750 ', '3000 ', '150 ', '1059 ', '11934 ', '27965 ', '216 ', '120 ', '649 ', '370 ', '4178504 ', '221579 ', '10800 ', '58509 ', '129685 ', '2456 ', '2921 ', '1151 ', '6590 ', '3000 ', '39797 ', '326 ', '913 ', '168286 ', '400 ', '314080 ', '637 ', '1710671 ', '12000 ', '10929 ', '1080 ', '40000 ', '43930257 ', '230318 ', '10500000 ', '13197 ', ' ', '30000 ', '324 ', '541909 ', '11164866 ', '163 ', '373 ', '20560 ', '40 ', '422937 ', '9358 ', '640 ', '919438 ', '40949 ', '5744 ', '10503 ', '42240 ', '102944 ', '500 ', '9782222 ', '11463 ', '17898 ', '1885 ', '19735 ', '1540 ', '4007 ', '153540 ', '606 ', '1353 ', '1956 ', '43824 ', '3942 ', '858 ', '287 ', '17764280 ', '106574 ', '9358 ', '11500 ', '92000 ', '315 ', '78095 ', '130 ', '74 ', '52854 ', '77 ', '811 ', '504 ', '401 ', '2856 ', '10546 ', '801 ', '1540 ', '1451 ', '1075 ', '78095 ', '7195 ', '3600 ', '76 ', '60 ', '405 ', '303 ', '303 ', '107888 ', '76000 ', '10000 ', '180 ', '745000 ', '12234 ', '292 ', '104 ', '60000 ', '2000 ', '165 ', '217 ', '1175 ', '704 ', '75128 ', '90 ', '90 ', '50 ', '71 ', '93239 ', '540 ', '105 ', '6611 ', '15 ', '372 ', '58000 ', '4960 ', '241600 ', '130000 ', '7062606 ', '740 ', '70 ', '2205 ', '10721 ', '640 ', '1000 ', '116 ', '1672 ', '322 ', '93600 ', '3060 ', '5879 ', '9200 ', '20000 ', '20867 ', ' ', '4143 ', '215063 ', '6000000 ', '21263 ', '63000000 ', '10190 ', '300 ', '12330 ', '5180 ', '756 ', '10000 ', '80 ', '1184 ', '1047 ', '777 ', '249 ', '414 ', ' ', '143 ', '7840 ', '30000 ', '35717 ', '135 ', '980 ', '5456 ', '120 ', '4095000 ', '7051 ', '240 ', '48204 ', '260000 ', '288000 ', '8300000 ', '125 ', '170 ', '141712 ', '3916 ', '6262 ', '420768 ', '1067371 ', '1385 ', '908 ', '546 ', '13956534 ', '15630426 ', '8992 ', '1687 ', '779 ', '1056 ', '590 ', '21643 ', '7750 ', '14057567 ', '27170754 ', '597 ', '329 ', '299 ', '20000 ', '26136 ', '1000 ', '399 ', '24017 ', '325834 ', '2916697 ', '22470 ', '189 ', '520 ', '826 ', '2279 ', '28764 ', '7107 ', '288000 ', '9800 ', '4760 ', '72 ', '1450 ', '170 ', '1984 ', '2955 ', '65532 ', '65919 ', '2111 ', '3810 ', '18 ', '244 ', '104 ', '139 ', '360177 ', '36733 ', '4480 ', '165474 ', '1985 ', '10000 ', '232 ', '150 ', '11 ', '14057567 ', '8760 ', '48 ', '6321 ', '3150 ', '17256 ', '187 ', '399 ', '14 ', '467 ', '597 ', '23700 ', '615 ', '6819 ', '1000 ', ' ', '2633 ', '200 ', '13028 ', '800 ', '1700 ', '521 ', '120000 ', '666 ', '88 ', '200 ', '2279 ', '23570 ', '10000 ', '37700 ', '1850 ', '11 ', '147270 ', '3150 ', '17256 ', '597 ', '7624 ', '314 ', '1197 ', '70 ', '7624 ', '26737 ', '10000 ', '13611 ', '12684 ', '48 ', '731 ', '731 ', '557 ', '107 ', '158716 ', '15744 ', '153000 ', '557 ', '36 ', '4200 ', '61069 ', '52417 ', '900 ', '35040 ', '4746 ', '73 ', '11000 ', '4465 ', '145 ', '202 ', '221 ', '597 ', '298 ', '110341 ', '705 ', '2101 ', '1765 ', '150 ', '4000 ', '6272 ', '1996 ', '35040 ', '75840 ', '400 ', '1014 ', '10129 ', '4000 ']

In [81]:
#scraping the No_of_Attribute 
noa=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
for i in noa:
    if i.text is None :
        No_of_Attribute.append("--") 
    else:
        No_of_Attribute.append(i.text)
print(len(No_of_Attribute),No_of_Attribute)

623 ['# Attributes', '8 ', '14 ', '38 ', '294 ', '279 ', '7 ', ' ', '69 ', '8 ', '26 ', '1 ', '4 ', '4 ', '9 ', '10 ', '34 ', '32 ', '13 ', '6 ', '14 ', '22 ', '36 ', '6 ', ' ', '6 ', '42 ', '15 ', ' ', '9 ', '9 ', '54 ', '39 ', '33 ', '20 ', ' ', ' ', ' ', '12 ', '8 ', '30 ', ' ', '10 ', '3 ', '5 ', '75 ', '19 ', '27 ', ' ', '19 ', '1558 ', '34 ', '4 ', '617 ', '12 ', '16 ', '7 ', '4 ', '16 ', '7 ', ' ', '56 ', '18 ', '8 ', '22 ', ' ', '58 ', ' ', '61 ', '7 ', ' ', '649 ', '22 ', '168 ', '168 ', '8 ', ' ', '10 ', '64 ', '16 ', '8 ', '17 ', ' ', ' ', '72 ', '4 ', '6 ', '10 ', '35 ', '35 ', '4 ', '102 ', '57 ', '22 ', '44 ', '45 ', ' ', ' ', '5 ', '9 ', '21 ', '32 ', '17 ', '16 ', '38 ', '21 ', '40 ', '13 ', '8 ', '17 ', ' ', ' ', '15 ', '22 ', '68 ', '40 ', '17 ', '89 ', ' ', '4 ', '12 ', ' ', ' ', '86 ', '72 ', '61 ', '12 ', '481 ', '42 ', ' ', ' ', ' ', ' ', ' ', ' ', '5 ', '90 ', ' ', '5 ', ' ', ' ', '14 ', '20 ', '13 ', '36 ', '19 ', '9 ', '18 ', '4 ', '60 ', '10 ', ' ', ' ', '10 ', '4 ', '3 ', '11 ', '11 ', ' ', '6 ', '13 ', ' ', '100000 ', '9 ', '101 ', '10000 ', '20000 ', '100000 ', '5000 ', '500 ', '73 ', '43 ', '23 ', '3 ', '5 ', ' ', '256 ', '591 ', '70 ', '91 ', '10 ', '128 ', '6 ', '12 ', '3231961 ', '5409 ', '26 ', ' ', ' ', '10 ', '23 ', '24 ', '13 ', '8 ', ' ', '27 ', '50 ', '90 ', '138672 ', ' ', '386 ', ' ', ' ', '12 ', '147 ', '6 ', '8 ', '27 ', '10000 ', '20000 ', '10000 ', '54877 ', '4702 ', '24 ', '29 ', '17 ', '3 ', '128 ', '10 ', '242 ', '120 ', ' ', '4 ', '13 ', '52 ', '47 ', '857 ', '9 ', '7 ', '200 ', '4 ', ' ', '561 ', '64 ', '8 ', '7 ', '10 ', '9 ', '4 ', '8 ', '77 ', '51 ', '18 ', '1950000 ', '18 ', '1300 ', '41 ', '6 ', '5625 ', '5 ', ' ', '7 ', '33 ', '5 ', '15 ', '9 ', '19 ', '5 ', '5 ', '1000000 ', '129 ', ' ', '20 ', '152 ', '24 ', '16 ', '35 ', '17 ', '5 ', '18 ', '28 ', '7 ', '309 ', '3 ', '6 ', ' ', ' ', '16 ', '13 ', '5 ', '6 ', '8 ', '2 ', '4 ', '148 ', '55 ', '17 ', '8 ', '42 ', '26 ', '50 ', '2 ', '281 ', '120 ', ' ', '6 ', '120432 ', '150000 ', '529 ', ' ', '16 ', '2500 ', '5 ', '68 ', '16 ', '100 ', '216 ', '23 ', '33 ', '140256 ', '19 ', '20 ', '20 ', '49 ', '12 ', '30 ', '5232 ', '20 ', '1 ', ' ', '61 ', '27 ', '53 ', '11 ', '25 ', '0 ', '20 ', '9 ', '3 ', '561 ', '82 ', '13 ', '16 ', '13 ', '28 ', '4 ', ' ', '24 ', '34 ', '8 ', '128 ', '15 ', '513 ', '7 ', '7 ', '5 ', '15 ', '480000 ', '11 ', '54 ', '561 ', '64 ', '6 ', '116 ', '19 ', ' ', '5812 ', '9 ', '32 ', '29 ', '67 ', ' ', '25 ', '6400 ', '10 ', '5 ', '13 ', '98 ', '36 ', '69 ', '2158859 ', '518 ', '15 ', '179 ', ' ', '12 ', '38 ', '65 ', '102 ', '86 ', '7 ', '53 ', '20 ', '1 ', '71 ', '29 ', '20531 ', '65 ', '3 ', '22 ', '38 ', '22 ', '4814 ', '698 ', '13 ', '10 ', '59 ', '56 ', '482 ', '171 ', '5 ', '500 ', '411 ', '8519 ', '21 ', '21 ', '171 ', '7 ', '49 ', '12 ', '3 ', '21 ', '9 ', '8 ', '7 ', '2 ', '11 ', '11 ', '173 ', '5 ', '15 ', '3 ', '105 ', '25000 ', ' ', '18 ', '21000 ', '115 ', '21 ', '206 ', '43680 ', '8 ', '10 ', '59 ', '10 ', '5 ', '5 ', '1000 ', '138 ', ' ', '16 ', '2 ', '10 ', ' ', '8 ', '6 ', '129 ', '81 ', '12 ', '6 ', '22 ', '18 ', '9 ', '754 ', '14 ', '5 ', ' ', ' ', '18 ', '7 ', '7 ', ' ', '7 ', '5 ', '6 ', '4 ', '18 ', '11 ', '25 ', ' ', '20 ', '12 ', '46 ', '9 ', '8 ', '49 ', '11 ', '8 ', '54 ', '36 ', '3916 ', '710 ', '18 ', '8 ', '29 ', '7 ', '9 ', '37 ', '6 ', '1024 ', '1024 ', '14 ', '7 ', '8265 ', '29 ', '25 ', '3 ', '115 ', '1 ', '12 ', '13 ', '200000 ', '6 ', '21 ', '4 ', '2400 ', '175 ', '10 ', '4714 ', '23 ', '17 ', '2 ', '9 ', '8 ', '280 ', '49 ', '3 ', '14 ', '19 ', ' ', '54 ', '8 ', '1087 ', '12 ', '3 ', '17 ', '8 ', '9 ', '12 ', '1656 ', '6 ', '2 ', '11 ', '533 ', '14 ', '84 ', '22 ', '16 ', '52 ', '19 ', '3 ', '14 ', '321 ', '13 ', '13 ', '55 ', '39 ', '4 ', '7 ', '79 ', '1 ', ' ', '14 ', '96 ', '21 ', ' ', '5 ', '2 ', '69 ', '9 ', '124 ', '20 ', '25 ', '11 ', '19 ', '9 ', '9 ', '5 ', '7 ', '4006 ', '2 ', '19 ', '4 ', '13 ', '55 ', '1 ', '7842 ', '15 ', '15 ', '70 ', '7842 ', '4 ', '14 ', '17 ', '23 ', '321 ', '1068 ', '1068 ', '5 ', '6 ', '4 ', ' ', '5 ', '5 ', '15 ', '7 ', '21 ', '9 ', '8 ', '11 ', '21 ', '22 ', '2 ', '241 ', '33 ', '29 ', '7 ', '1 ', ' ', '4 ', '11 ', '47 ', '10 ', '3 ', '2 ', '632 ', '6826 ', '11 ', '525 ', '50 ', '7 ', '16 ', '2 ']

In [82]:
#scraping the Year 
y=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p")
for i in y:
    if i.text is None :
        Year.append("--") 
    else:
        Year.append(i.text)
print(len(Year),Year)

623 ['Year', '1995 ', '1996 ', ' ', '1998 ', '1998 ', '1992 ', '1987 ', '1992 ', '1993 ', '1987 ', '1994 ', '1994 ', ' ', '1988 ', '1992 ', '1995 ', '1995 ', '1990 ', '1997 ', '1996 ', '1988 ', '1989 ', '1994 ', ' ', ' ', '1995 ', ' ', '1992 ', '1987 ', '1997 ', '1998 ', '1995 ', '1998 ', ' ', ' ', '1994 ', ' ', '1989 ', '1996 ', '1990 ', '1990 ', '1987 ', '1999 ', '1989 ', '1988 ', '1988 ', '1989 ', ' ', '1990 ', '1998 ', '1989 ', '1988 ', '1994 ', '1990 ', '1988 ', '1988 ', '1990 ', '1991 ', '1990 ', ' ', '1992 ', '1988 ', '1990 ', '1996 ', '1995 ', '1990 ', ' ', '1992 ', '1992 ', '1994 ', ' ', '1987 ', '1994 ', '1994 ', '1997 ', '1991 ', '1995 ', '1998 ', '1998 ', '1993 ', '1988 ', ' ', ' ', '1992 ', '1993 ', '1988 ', '1989 ', '1988 ', '1987 ', '1993 ', '1988 ', '1999 ', '2001 ', '2001 ', ' ', '1992 ', '1993 ', '1997 ', '1991 ', '1987 ', '1994 ', '1988 ', '1987 ', '1993 ', '1988 ', '1988 ', '1991 ', '1996 ', '1990 ', ' ', '1999 ', '1999 ', '2002 ', ' ', '2000 ', '1999 ', '1999 ', '2001 ', '1999 ', '1999 ', '2000 ', '1999 ', '2000 ', '1999 ', '1999 ', ' ', '1998 ', '1999 ', '2001 ', '1999 ', ' ', '2003 ', '1999 ', '1999 ', '1997 ', '1999 ', '1999 ', '1998 ', ' ', ' ', ' ', '1994 ', ' ', '1993 ', '1990 ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '1989 ', '2006 ', '2006 ', '2007 ', '2007 ', '2007 ', '2007 ', '2008 ', '2008 ', '2008 ', '2007 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2009 ', '2008 ', '2008 ', '2008 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2010 ', '2009 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2014 ', '2013 ', '2013 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2015 ', '2014 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2016 ', '2017 ', '2016 ', '2017 ', '2017 ', '2016 ', '2016 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2018 ', '2018 ', '2016 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ']

In [83]:
UCI=pd.DataFrame([])
UCI['Dataset_Name']=Dataset_Name[:100]
UCI['Data_Type']=Data_Type[:100]
UCI['Task']=Task[:100]
UCI['Attribute_Type']=Attribute_Type[:100]
UCI['No_of_Instances']=No_of_Instances[:100]
UCI['No_of_Attribute']=No_of_Attribute[:100]
UCI['Year']=Year[:100]
UCI

,Dataset_Name,Data_Type,Task,Attribute_Type,No_of_Instances,No_of_Attribute,Year
0,Abalone,Data Types,Default Task,Attribute Types,# Instances,# Attributes,Year
1,Adult,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Annealing,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Anonymous Microsoft Web Data,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Arrhythmia,,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
95,Statlog Project,Multivariate,Clustering,"Categorical, Integer",76,45,
96,Student Loan Relational,,,,,,1992
97,Teaching Assistant Evaluation,Domain-Theory,,,1000,,1993
98,Tic-Tac-Toe Endgame,Multivariate,Classification,"Categorical, Integer",151,5,1997
99,Thyroid Disease,Multivariate,Classification,Categorical,958,9,1991

In [84]:
UCI.to_csv("ml_repo.csv")

### 9. Scrape the details of Data science recruiters Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details:

A) Name

B) Designation

C)Company

D)Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [3]:
driver.get('https://www.naukri.com/hr-recruiters-consultants')

In [37]:
name=[]
designation=[]
company=[]
skill=[]
location=[]

In [38]:
#scraping the name 

n=driver.find_elements(By.XPATH,'//*[@class="fl ellipsis"]')

for i in n:
    if i is " ":
        name.append('--')
    else:
        name.append(i.text)
        
print(len(name),name)

50 ['Santhosh Kumar', 'Gauri Bhosle', 'Surendra R', 'Neha Pandey', 'Vinita Raut', 'aditya pungavkar', 'BALA Sakthivelmuthu', 'Prarit Gupta', 'Raghu Hrexecutive', 'Take jobs', 'iNFIN Technologies', 'Punit Kumar Bhidodiya', 'Ishan Ahmed', 'Sreekanth Menon', 'TechCube IT Services Pvt Ltd', 'Fatte Chand Soni', 'Koustav Bose', 'Vaishambi Saxena', 'Be Tuned Solutions', 'Prerna Kashyap', 'Sunil Joshi', 'Stella', 'Pranav Varia', 'Emma Rodrigues', 'Sonal Sharma', 'Sita Chhetri', 'Nikhil Bhardwaj', 'Vibhuti Bhatt', 'Pushkar Gupta', 'Anjali Gupta', 'katrina Dikoster', 'shalini gupta', 'Pradeep Naik', 'K Gayaj', 'Ms Chitra Doshi', 'Deepak Tripathi', 'ASHISH MAURYA', 'Charmi Dave', 'Lilly Mohindru', 'Nivedita Rawat', 'Sandeep Samantaray', 'Vijay Bharadvaj', 'iota Academy', 'Arindam Bhattacharjee', 'Jyoti Chopra', 'Marlin', 'Aditya Choudhry', 'Nimble Organics', 'RAJ KUMAR PANDEY', 'BVL REALTY']

In [39]:
# scraping the designation

jt=driver.find_elements(By.XPATH,'//span[@class="ellipsis clr"]')
for i in jt:
    if i.text is None :
        designation.append("--") 
    else:
        designation.append(i.text)
print(len(designation),designation)

50 ['Associate Manager Human Resources', 'Human Resources', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Company Recruiter', 'Human Resource Manager', 'Human Resource manager', 'Human Resources', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Generalist', 'human resource manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'Regional HR Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Regional HR Manager', 'Regional HR Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'Human Resources', 'Human Resources', 'Human Resource Manager', 'Human Resources', 'Human Resource Manager', 'Human Resource manager', 'Associate Manager Human Resources', 'Human Resource Manager', 'Human resources', 'Human Resource Manager', 'Human Resource Manager', 'Human Resource Manager', 'HUMAN RESOURCES']

In [50]:
company=[]

In [51]:
#scraping the Company_Name 
cn=driver.find_elements(By.XPATH,'//*[@class="highlightable"]/a[2]')
for i in cn:
    if i.text is None :
        company.append("--") 
    else:
        company.append(i.text)
print(len(company),company)

50 ['Maveric Systems', 'TCRC', 'DSR Design &amp; Engineering Solutions', 'Ingenious E-Brain Solutions Private Limited', 'Xpansion HR Solutions Private Limited', 'IP ASSOCIATES', 'E Vel', 'HMS Relations Management', 'IQs soft', 'Take Jobs', 'Infin Software Technologies Pvt. Ltd', 'Exatip Technologies', 'Jute Wonders Unlimited', 'Sterlite Technologies Ltd. Elitecore', 'TechCube IT Services Pvt Ltd', 'Tetraskelion Softwares (P) Ltd', 'KKR BOSE DESIGN SERVICES PVT LTD', '22Feet Tribal Worldwide (DDB Worldwide)', 'Be-Tuned Solutions', 'CoconutEvent', 'Ravi infra- Build Projects Private limited,', 'Treselle Software Pvt Ltd', 'Smart Technospace Pvt Ltd', 'Sahil International', 'Paragyte Technologies', 'Sarbottam Cement Pvt. Ltd. / Laxmi Steels...', 'Larsen And Toubro', 'Gujarat Ambuja Exports limited', 'Nityo Infotech', 'Reliance Communications', 'Cambridge Learning System', 'Cambridge Learning System', 'Akamai Technologies', 'HCG Cancer Care', 'Rasson Energy India Pvt. Ltd.', 'Influence Technolabs Pvt Ltd', 'STEP IN SOLUTIONS', 'Charmi D Dave', 'Orion eSolutions.Pvt.Ltd', 'Miracle Group', 'Jones Lang La Salle', 'Novel Group', 'iota Academy', 'Perfetti Van Melle India', 'Vikas Kochar &amp; Associates', 'MarlinByte Software Solutions Pvt. Ltd.', 'Motilal Oswal Securities Limited', 'Nimble Organics Jobs', 'United Telecoms Limited', 'BVL GROUP']

In [47]:
#scraping the Location 
loc=driver.find_elements(By.XPATH,'//*[@class="highlightable"]/span[2]/small')
for i in loc:
    if i.text is None :
        location.append("--") 
    else:
        location.append(i.text)
print(len(location),location)

50 ['Chennai', 'Mumbai', 'Hyderabad / Secunderabad', 'Gurgaon', 'Pune', 'Pune', 'Madurai', 'Delhi', 'Bengaluru / Bangalore', 'Delhi', 'Chandigarh', 'Indore', 'Delhi', 'Ahmedabad', 'Mohali', 'Jaipur', 'Mumbai', 'Bengaluru / Bangalore', 'Mohali', 'Mumbai', 'Udaipur', 'Chennai', 'Surat', 'Mumbai', 'Pune', 'Nepal - (Kathmandu)', 'Kolkata', 'Ahmedabad', 'Delhi', 'Gurgaon', 'Hyderabad / Secunderabad', 'Delhi', 'Bengaluru / Bangalore', 'Bengaluru / Bangalore', 'Ahmedabad', 'Delhi', 'Mumbai', 'Ahmedabad', 'Mohali', 'Chandigarh', 'Bengaluru / Bangalore', 'Bengaluru / Bangalore', 'Kolkata', 'Kolkata', 'Delhi', 'Delhi', 'Amritsar', 'Bengaluru / Bangalore', 'Noida', 'Bengaluru / Bangalore']

In [52]:
#scraping the Skill 
sk=driver.find_elements(By.XPATH,'//*[@class="recInfo"]/div[2]')
for i in sk:
    if i.text is None :
        skill.append("--") 
    else:
        skill.append(i.text)
print(len(skill),skill)

50 ['It Recruitment, Campus Recruitment, Campus Hiring, Software Testing', 'Operation Executive, Jr. Chemist/ Chemist, Audit, Chemist, Operation Coordination, Documentation, Typist, Data Entry, Operation, Inspection, Survey, Analysis', 'Design Engineering, AutoCAD, Solid Works', 'B.tech, Operations, Business Development, Business Analysis, Business Intelligence, Business Research, Market Research, Ipr', 'Bde, Accounting, Education Counseling, Sales, Inside Sales, Telecalling, International Bpo, International Call Center', 'Autocad, Google Sketchup, Architectural Design, Architecture, Working Drawings', 'Html, Css, Javascript, Ui Development, Java, Android, Ios, Liferay Developer, Sfdc, Cloud Fusion, Atg Developer', 'Counter Sales, Sales', 'Java/J2ee ( Core Java, Struts, Hibernate, Servlets, JSP, Spring), .Net ( C# asp.net, Vb.net, Sql Server ), Testing tools &amp;ndash;Manual / Automation ( QTP', 'tally, Bank Reconciliation, billing, electricals, Cable Laying, Fault Finding, Team Leading, Back Office, Personal Loans, operations, design', 'Technical, PHP, Web Development, Web Technologies, Wordpress, Javascript, HTML, OSCommerce, Codeigniter, JQuery, CSS, Facebook, Seo, Smo, Smm, Search Engine', 'Software Development, Business Development', 'Back Office', 'C++, Java/j2ee, C, Networking, Radius, Diameter, Aaa, Testing, Billing, Mediation, Charging, Rating, Policy Control, Provisioning, Oss/bss, Core', 'Skills- Technical Troubleshooting / Sales / Up-Selling / Order Processing / Customer Services / Contact Center Account Management - Roles- Representatives /', '.Net, Java, PHP, Android, Testing, IOS, Web and Graphic, UI, SAP, Quality Assurance / Testing, Manual Testing, Software Testing, Web Applications, Web', 'Ravit', 'Magento, PHP, Content, Design, DotNet, BD', 'Content Writing, Content Development, Technical Writing, Creative Writing, Bidder Required, Online Bidding, Business Development', 'English Literature, Copy Writing, Content Writing, Copy Editing, Proof Reading, Content Editing, Content', 'BDM/ BDO, Branch Manager, Senior Branch manager, Chartered Accountant, Marketing Executive, Operation Executive, accountant, Account Management, account', 'Java, Database, Front End, Big Data, Cloud Computing, Salesforce, Testing, Data Scientist, DevOps, Lead Generation, Mobile, Technical Architect, Technical PM', 'Project Management, Sharp Supervision, Leadership, ready to travel, excellent communication skill, drywall/PEB knowledge, Project Planning, Project', 'Marketing, Customer Service, Finance, Telecom, Graphic Designing, System Administration System Engineer, It Executive, System Technician, Hardware And', 'java, support, ui designer/developer, Java Script, html, spring, hibernate, React.js, .net, Node.js, Recruitment', 'Erection Commissioning, Stores, Installation, Material Receipt, Project Scheduling, Mechanical Engineering, B.e, Maintenance, Electrical Engineering', 'Thermodynamics, Heat Transfer, Product Quality, Mechanical Engineering, B.e, Diploma, Maintenance, B.tech, Autocad, Mechanical Maintenance, Mechanical Design', 'Good Communication Skill, Confident Personality, Store Executive, Account Executive, Public Relation Officer, Purchase Executive, Sr. Administrator', 'Myntra, Redbus, Digital Vidya, Accolite Software, Hiya', 'Software Development, Technical, It, Web Designing, Sales, Management, Relationship Management, Real Estate Marketing, Sales Management, Selling, New Business', 'Education Industry, Educational Sales, Educational Administration, Educational Marketing', 'Web Designing, Education, Educational Sales, Educational Marketing, Sales, Advertising, Public Relations, Marketing Campaigns, Promotions, Events, Social', 'Internet Technologies, Media Streaming, Information Security, Network Security, Presales Consultant', 'health care services, Oncologist, Center Management, Marketing, International Marketing, Cradit Controle, Hr Managers, Accounts Managers, Quality Control', 'Procurement, Supply Chain, Engineer, Marketing, Project Management, Supply Chain Management, Sales, Business Development', 'HTML, CSS, .Net, Dream Weaver, Photoshop, Java Script, Visual Studio, Android, XML, HTML5, C, Java, JQuery, JSON, J2ME, SDK, IDE, JAVA, JQUERY', 'Javascript, MVC, PHP, UX, Web Technologies, Product Management, Software Services', 'Store Keeping, Stores Maintenance, Inventory, Store Management', 'Developers, IOS DEVELOPERS, IOS, IPHONE, Android Developer, Android, Business Development, Business Analytics, Online Bidding, Bidder, Internet Marketing, Mass', 'Developers, Project Mangers, Quality Assurance, Accounting, Content Writing, Android, Ios', 'Sr. Manager, Manager, Management, Facilities, Facility Management, Hotel, Cafeteria Management, Event Management, Corporate Events, Daily Operations', 'Business Development, Client Relationship Management, Project Engineering, It Hardware, Material Procurement, Project Procurement, Digital Marketing', 'Curriculum Development, physics, Teaching, Iit, Iit-jee, Jee, Jee Main, Advanced, Neet, Entrance Exam, Competitive Exam, Nit, T, Math', 'Channel Sales, Fmcg Sales, Sales, Channel Distribution, Distribution, Distribution Network, Business Development', 'Executive, Managers, Data Entry Operation, Data Entry Operator, Communication Skills, Audit, Bangalore', 'Web Designing, Web Development, Content Writing, seo, Digital Marketing, Business Development, Web Technologies, Php, Wordpress', 'Sales/ Marketing, Sales Management, Client Acquisition, Rm, Hni Sales, Hni Acquisition, Hni Client Handling, Mutual Funds, Sip, Equity, Broking, Financial', 'Executive, Front Office, MS Office, English Speaker, Computers, Receptionist, Marketing Executives, Operations, Management', 'Channel Sales Management, Territory Sales Management, Area Sales Management, Channel Sales, Distributor Sales, Dealer Management, Business Development', 'accounting, auditing, finance, payments, reporting, Receptionist Activities, Front Office, Communication Skills, MS Office, Administration, Security']

In [54]:
JOB=pd.DataFrame([])
JOB['Name']=name
JOB['DESIGNATION']=designation
JOB['Company']=company
JOB['Skill']=skill
JOB['Location']=location
JOB

,Name,DESIGNATION,Company,Skill,Location
0,Santhosh Kumar,Associate Manager Human Resources,Maveric Systems,"It Recruitment, Campus Recruitment, Campus Hir...",Chennai
1,Gauri Bhosle,Human Resources,TCRC,"Operation Executive, Jr. Chemist/ Chemist, Aud...",Mumbai
2,Surendra R,Company Recruiter,DSR Design &amp; Engineering Solutions,"Design Engineering, AutoCAD, Solid Works",Hyderabad / Secunderabad
3,Neha Pandey,Company Recruiter,Ingenious E-Brain Solutions Private Limited,"B.tech, Operations, Business Development, Busi...",Gurgaon
4,Vinita Raut,Company Recruiter,Xpansion HR Solutions Private Limited,"Bde, Accounting, Education Counseling, Sales, ...",Pune
5,aditya pungavkar,Company Recruiter,IP ASSOCIATES,"Autocad, Google Sketchup, Architectural Design...",Pune
6,BALA Sakthivelmuthu,Company Recruiter,E Vel,"Html, Css, Javascript, Ui Development, Java, A...",Madurai
7,Prarit Gupta,Human Resource Manager,HMS Relations Management,"Counter Sales, Sales",Delhi
8,Raghu Hrexecutive,Human Resource manager,IQs soft,"Java/J2ee ( Core Java, Struts, Hibernate, Serv...",Bengaluru / Bangalore
9,Take jobs,Human Resources,Take Jobs,"tally, Bank Reconciliation, billing, electrica...",Delhi
10,iNFIN Technologies,Human Resources,Infin Software Technologies Pvt. Ltd,"Technical, PHP, Web Development, Web Technolog...",Chandigarh
11,Punit Kumar Bhidodiya,Human Resource Manager,Exatip Technologies,"Software Development, Business Development",Indore
12,Ishan Ahmed,Human Resource Manager,Jute Wonders Unlimited,Back Office,Delhi
13,Sreekanth Menon,Human Resources,Sterlite Technologies Ltd. Elitecore,"C++, Java/j2ee, C, Networking, Radius, Diamete...",Ahmedabad
14,TechCube IT Services Pvt Ltd,Human Resource Manager,TechCube IT Services Pvt Ltd,Skills- Technical Troubleshooting / Sales / Up...,Mohali
15,Fatte Chand Soni,Human Resource Generalist,Tetraskelion Softwares (P) Ltd,".Net, Java, PHP, Android, Testing, IOS, Web an...",Jaipur
16,Koustav Bose,human resource manager,KKR BOSE DESIGN SERVICES PVT LTD,Ravit,Mumbai
17,Vaishambi Saxena,Human Resources,22Feet Tribal Worldwide (DDB Worldwide),"Magento, PHP, Content, Design, DotNet, BD",Bengaluru / Bangalore
18,Be Tuned Solutions,Human Resource Manager,Be-Tuned Solutions,"Content Writing, Content Development, Technica...",Mohali
19,Prerna Kashyap,Human Resource Manager,CoconutEvent,"English Literature, Copy Writing, Content Writ...",Mumbai
20,Sunil Joshi,Human Resource Manager,"Ravi infra- Build Projects Private limited,","BDM/ BDO, Branch Manager, Senior Branch manage...",Udaipur
21,Stella,Human Resources,Treselle Software Pvt Ltd,"Java, Database, Front End, Big Data, Cloud Com...",Chennai
22,Pranav Varia,Human Resource Manager,Smart Technospace Pvt Ltd,"Project Management, Sharp Supervision, Leaders...",Surat
23,Emma Rodrigues,Human Resource Manager,Sahil International,"Marketing, Customer Service, Finance, Telecom,...",Mumbai
24,Sonal Sharma,Human Resource Manager,Paragyte Technologies,"java, support, ui designer/developer, Java Scr...",Pune
25,Sita Chhetri,Human Resource Manager,Sarbottam Cement Pvt. Ltd. / Laxmi Steels...,"Erection Commissioning, Stores, Installation, ...",Nepal - (Kathmandu)
26,Nikhil Bhardwaj,Regional HR Manager,Larsen And Toubro,"Thermodynamics, Heat Transfer, Product Quality...",Kolkata
27,Vibhuti Bhatt,Human Resources,Gujarat Ambuja Exports limited,"Good Communication Skill, Confident Personalit...",Ahmedabad
28,Pushkar Gupta,Human Resource Manager,Nityo Infotech,"Myntra, Redbus, Digital Vidya, Accolite Softwa...",Delhi
29,Anjali Gupta,Human Resource Manager,Reliance Communications,"Software Development, Technical, It, Web Desig...",Gurgaon
30,katrina Dikoster,Regional HR Manager,Cambridge Learning System,"Education Industry, Educational Sales, Educati...",Hyderabad / Secunderabad
31,shalini gupta,Regional HR Manager,Cambridge Learning System,"Web Designing, Education, Educational Sales, E...",Delhi
32,Pradeep Naik,Human Resources,Akamai Technologies,"Internet Technologies, Media Streaming, Inform...",Bengaluru / Bangalore
33,K Gayaj,Human Resource Manager,HCG Cancer Care,"health care services, Oncologist, Center Manag...",Bengaluru / Bangalore
34,Ms Chitra Doshi,Human Resource Manager,Rasson Energy India Pvt. Ltd.,"Procurement, Supply Chain, Engineer, Marketing...",Ahmedabad
35,Deepak Tripathi,Human Resource Manager,Influence Technolabs Pvt Ltd,"HTML, CSS, .Net, Dream Weaver, Photoshop, Java...",Delhi
36,ASHISH MAURYA,Human Resource Manager,STEP IN SOLUTIONS,"Javascript, MVC, PHP, UX, Web Technologies, Pr...",Mumbai
37,Charmi Dave,Human Resources,Charmi D Dave,"Store Keeping, Stores Maintenance, Inventory, ...",Ahmedabad
38,Lilly Mohindru,Human Resources,Orion eSolutions.Pvt.Ltd,"Developers, IOS DEVELOPERS, IOS, IPHONE, Andro...",Mohali
39,Nivedita Rawat,Human Resource Manager,Miracle Group,"Developers, Project Mangers, Quality Assurance...",Chandigarh
40,Sandeep Samantaray,Human Resources,Jones Lang La Salle,"Sr. Manager, Manager, Management, Facilities, ...",Bengaluru / Bangalore
41,Vijay Bharadvaj,Human Resource Manager,Novel Group,"Business Development, Client Relationship Mana...",Bengaluru / Bangalore
42,iota Academy,Human Resource manager,iota Academy,"Curriculum Development, physics, Teaching, Iit...",Kolkata
43,Arindam Bhattacharjee,Associate Manager Human Resources,Perfetti Van Melle India,"Channel Sales, Fmcg Sales, Sales, Channel Dist...",Kolkata
44,Jyoti Chopra,Human Resource Manager,Vikas Kochar &amp; Associates,"Executive, Managers, Data Entry Operation, Dat...",Delhi
45,Marlin,Human resources,MarlinByte Software Solutions Pvt. Ltd.,"Web Designing, Web Development, Content Writin...",Delhi
46,Aditya Choudhry,Human Resource Manager,Motilal Oswal Securities Limited,"Sales/ Marketing, Sales Management, Client Acq...",Amritsar
47,Nimble Organics,Human Resource Manager,Nimble Organics Jobs,"Executive, Front Office, MS Office, English Sp...",Bengaluru / Bangalore
48,RAJ KUMAR PANDEY,Human Resource Manager,United Telecoms Limited,"Channel Sales Management, Territory Sales Mana...",Noida
49,BVL REALTY,HUMAN RESOURCES,BVL GROUP,"accounting, auditing, finance, payments, repor...",Bengaluru / Bangalore

In [55]:
JOB.to_csv('naukri_hr_consluntant.csv')